### PR TITLE
Fix: Compressed & Cached JS files

### LINKED ISSUE #4073: [BUG] Compressed & Cached JS files
I see, that JS files are not compressed and no a cache time is set

grafik

I found out, that a `.htaccess` file in ./p/scripts with this content could set a cache-control value
```
<IfModule mod_expires.c>
	ExpiresActive	on
	ExpiresByType application/x-javascript "access plus 1 month"
	ExpiresByType text/javascript "access plus 1 month"
	ExpiresByType application/javascript "access plus 1 month"
</IfModule>
```

But I could not find the reason, why CSS files are compressed but not the JS files.

Any idea?

### PR DESCRIPTION
**Pull request by math-GH**
Closes #4073

Changes proposed in this pull request:

- .htaccess

How to test the feature manually:

1. check javascript files in browser development tool: see cached and compression information

Pull request checklist:

- [x ] clear commit messages
- [x ] code manually tested

### CODE REVIEW

**Comment by Alkarex** [comment]
@math-GH `application/x-javascript` is not correct and probably a sign of a wrong Apache setup.
Please try this patch instead https://github.com/FreshRSS/FreshRSS/pull/4075/commits/d940af13e0d5a2a5bc7b08aac95fea63dc0d1105

* https://developer.mozilla.org/en-US/docs/Learn/Server-side/Configuring_server_MIME_types
* https://www.iana.org/assignments/media-types/media-types.xhtml

For reference, `application/javascript` is correctly defined as default on Alpine and Debian / Ubuntu:

```console
# Alpine
$ docker run --rm freshrss/freshrss:edge-alpine grep -i '/javascript' -r /etc/
/etc/apache2/mime.types:application/javascript                          js
/etc/apache2/mime.types:# text/javascript

# Debian / Ubuntu
$ docker run --rm freshrss/freshrss:edge grep -i '/javascript' -r /etc/
/etc/apache2/mods-available/deflate.conf:               AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css text/javascript
/etc/apache2/mods-available/deflate.conf:               AddOutputFilterByType DEFLATE application/x-javascript application/javascript application/ecmascript
/etc/apache2/mods-available/http2.conf:    # H2PushPriority  application/javascript  interleaved
/etc/mime.types:application/javascript                          js mjs
```

**Comment by math-GH** [comment]
Without d940af1
JS in /scripts/
= `application/x-javascript`
grafik

JS via ext.php
= `application/javascript`
grafik

**Comment by Alkarex** [comment]
@math-GH Is your test done with this patch applied?

**Comment by math-GH** [comment]
> @math-GH Is your test done with this patch applied?

Thanks for your fix. It works fine :)

**Pull request merged**
