### PR TITLE
Add section for text import

### LINKED ISSUE #663: Ajout de flux multiples
Il serait bon d'avoir une fonctionnalité qui permet l'ajout de plusieurs flux d'un coup, y aurais deux méthodologie que j'ai en tête:
- Une textarea, un flux par ligne, une catégorie pour tous les flux.
- Ajout de flux multiple dynamique, on nous affiche deux lignes (à chaque fois, un champ pour le flux, et un select pour la catégorie), si les deux lignes sont remplies, on affiche une 3ème ligne vierge, prêt à être rempli, etc etc

### PR DESCRIPTION
**Pull request by aledeg**
Closes #663

Changes proposed in this pull request:

- add section for text import in documentation

Pull request checklist:

- [x] clear commit messages
- [ ] code manually tested
- [ ] unit tests written (optional if too hard)
- [x] documentation updated

[Additional information can be found in the documentation](https://github.com/FreshRSS/FreshRSS/tree/master/docs/en/developers/04_Pull_requests.md).

### CODE REVIEW

**Comment by aledeg** [comment]
@Frenzie Could you check if I need to do more things for the documentation. I know you worked on that but I did not follow through what you've done. Thanks!

**Review by Alkarex — APPROVED** [review]

**Comment by Frenzie** [comment]
@aledeg This is fine, but you can also use po4a, provided you have a sufficiently recent version. At least 0.57 possibly? Newer than whatever's in the previous Debian/Ubuntu stable anyway.

Using po4a makes it slightly easier to keep things in sync, but it's not a necessity. And it's clever enough to pick up your changes and to integrate them in the PO files whenever it's run next.

**Comment by aledeg** [comment]
@Frenzie I tried with po4a using the script `translation-update.sh`. It changes a lot of things back to English. The French version has been altered losing the translation made. Here is the list of file changes after running the script:
```
On branch doc/import-text
Your branch is up to date with 'origin/doc/import-text'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    ../data/do-install.txt
        modified:   fr/contributing.md
        modified:   fr/developers/01_First_steps.md
        modified:   fr/developers/03_Backend/05_Extensions.md
        modified:   fr/developers/03_Running_tests.md
        modified:   fr/index.md
        modified:   fr/users/03_Main_view.md
        modified:   fr/users/04_Subscriptions.md
        modified:   fr/users/06_Fever_API.md
        modified:   fr/users/06_Mobile_access.md
        modified:   fr/users/07_Frequently_Asked_Questions.md
        modified:   i18n/freshrss.fr.po
        modified:   i18n/templates/freshrss.pot
        modified:   po4a.conf

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        ../.idea/
        fr/developers/04_Pull_requests.md
        fr/developers/Minz/
        fr/internationalization.md

no changes added to commit (use "git add" and/or "git commit -a")
```
Do you have any guidance on what I need to do?

**Comment by Frenzie** [comment]
You may be overlooking the po/pot files. Is it in there but marked dirty
for example?

**Comment by aledeg** [comment]
I do not understand what you are saying.

Is there some documentation on how to handle the `translation-update.sh` script I can use?
Is there something else I need to do?
Should I worry about those changes or just keep this PR as-is?

**Comment by Frenzie** [comment]
This PR is fine.

The purpose of po4a is to make maintenance significantly easier. It's cleverly multidirectional in ways that gettext is not. But you do need to use gettext tooling at some point to actually use its conveniences. That can be manual, but e.g. poedit/virtaal/lokalize are much easier.

You say some French stuff is lost in the output. That's most likely a string marked dirty. Which roughly means it used to match but needs double checking and approval (and possibly updating). It's a desired quality control thing.

**Comment by aledeg** [comment]
Ok, I think I understand now!
I let the PR as-is and will dig in po files later to understand how they work.

**Comment by Frenzie** [comment]
Sorry, I meant `fuzzy`, not `dirty`.

```
#: frontend/apps/reader/modules/readercropping.lua:68
#, fuzzy
msgid "Apply crop"
msgstr "Appliquer"
```

But it's much quicker in a program like Lokalize:
Screenshot_2020-12-29_17-01-10

As you can see in this case it would need to be updated, but in your case (at least in this PR) you'd merely have to remove the `fuzzy`.

**Comment by Frenzie** [comment]
@aledeg There are a few sections that don't seem to be automatically matched in the latest po4a for some reason, but I suspect you were misled by a whole big page worth of material that was replaced with:

```diff
+This part [is explained here](/docs/en/internationalization.md).
```

In any case, it only makes maintenance actually possible, not actually easy. ^_^

**Pull request merged**
