### PR TITLE
Add Swage Theme

### PR DESCRIPTION
**Pull request by pattems**
Add a new Theme to FreshRSS.

This theme is a bit of a UI departure from other themes, especially on mobile:

original

capture

### CODE REVIEW

**Comment by Alkarex** [comment]
Not a big deal, but it looks like there is a couple of glitches in the /dev branch (which is the branch where the next version of FreshRSS are baked)

image

image

**Comment by Alkarex** [comment]
Another little glitch, when scrolling:

image

**Comment by pattems** [comment]
I've updated the credits. I'll get a dev branch instance set up this evening and see if I can get those glitches ironed out; I haven't looked at diffs yet, but I suspect I know what's going on and that it'll be pretty easy to straighten out.

To be clear, is the second glitch you found also with the dev branch?

**Comment by Alkarex** [comment]
Yes indeed, my tests were all done in the dev branch. I think the easiest for you is just to merge your /dev in your /master so you can keep your current PR.

**Comment by pattems** [comment]
That should hopefully take care of things!

**Comment by Alkarex** [comment]
Looks perfect. Thanks again 😃

**Comment by pattems** [comment]
I fixed the bug with the config page; it was caused by being a little over-zealous with my last fix, along with the menu width issue. Since this pull request has been merged, do I need to open a new one to get the changes to you? I'm a little unfamiliar with git operations here.

**Comment by Frenzie** [comment]
Yes, a new PR is the way to go! :-)

**Comment by GLLM** [comment]
Edit : Hello !!

@Alkarex : i see that the CSS now enable the merg of the 2 upper bars + the logo can now be place in the left pane, as I suggested inhttps://github.com/FreshRSS/FreshRSS/issues/1983
What has enabled this ?
I'm very interested :) :)

Edit2 : thanks

**Comment by Alkarex** [comment]
@GLLM I am not sure to understand your question. The new theme that @pattems has kindly provided does that with pure CSS (you can check the precise CSS rules in the source or in your browser's Web inspector), taking advantage of absolute position, fixed, table layout, etc. It is possible to move any element anywhere on the page. https://github.com//issues/1983 was more about providing some options to change those things in existing themes, but with this nice new Swage theme, I do not think it is needed any more.

**Comment by Alkarex** [comment]
@pattems Please do not hesitate to ask if you are facing any problem with the git flow

**Comment by pattems** [comment]
@Alwaysin You're most welcome! It's good to hear other people are enjoying my work.

The configure-feeds buttons glitch is regrettable, but it's not a problem I can think of any way to really practically tackle with just CSS. It should be a fixable problem though, and I'll look into it as soon as time allows.

Good call on highlighting the menu you're in; that didn't even occur to me, but I'll certainly stick it on my to-do list.

**Comment by Alkarex** [comment]
@pattems Feel free to make new pull requests. Those will be included in the next minor release 1.12.1.

**Comment by Alwaysin** [comment]
@pattems I've just noticed that the login screen using your theme is kinda weird ("Login" cut off, FreshRSS is white on white so not visible, and boxes not visible enough I think):
image

**Comment by pattems** [comment]
@Alwaysin good catch. Two of those three should be simple fixes. I'm not sure about the logo, but I think that should be fairly trivial as well. I'm a bit swamped at the moment, but I should have a PR to fix that out by the end of the weekend.

**Pull request merged**
