### PR TITLE
Remove Minz validation

### PR DESCRIPTION
**Pull request by aledeg**
Changes proposed in this pull request:

- Remove Minz validation

How to test the feature manually:

1. open installation check menu

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested
- [ ] unit tests written (optional if too hard)
- [ ] documentation updated

[Additional information can be found in the documentation](https://github.com/FreshRSS/FreshRSS/tree/master/docs/en/developers/04_Pull_requests.md).

It should have been done during #3302.

### CODE REVIEW

**Comment by Alkarex** [comment]
Could the following be removed as well?

https://github.com/FreshRSS/FreshRSS/blob/54f04e1233b59f1b62c8a79060b59c786a142792/app/i18n/en/install.php#L75-L78

**Comment by aledeg** [comment]
Done

**Comment by Alkarex** [comment]
A bit more here:
https://github.com/FreshRSS/FreshRSS/blob/13688825f2d76cb718774b122111a31aa071c51e/cli/i18n/ignore/en.php#L28-L29

**Comment by aledeg** [comment]
done

**Pull request merged**
