### PR TITLE
Fix extension file search

### PR DESCRIPTION
**Pull request by aledeg**
Changes proposed in this pull request:

- Fix extension file search
-
-

How to test the feature manually:

1.
2.
3.

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested
- [ ] unit tests written (optional if too hard)
- [ ] documentation updated

[Additional information can be found in the documentation](https://github.com/FreshRSS/FreshRSS/tree/master/docs/en/developers/04_Pull_requests.md).

Before, it was possible to retrieve only the files from extensions. Thus
making core extension files unreachable.
Now, the selected file is search through all extensions folders.

### CODE REVIEW

**Comment by aledeg** [comment]
This modification is needed for the theme extensions.

**Comment by Alkarex** [comment]
If possible, it would be nice to avoid searching on disk, but that should do it for now

**Comment by aledeg** [comment]
How do you think we should do that?

**Comment by Alkarex** [comment]
For instance by including the type of extension as a prefix of the extension name

**Pull request merged**
