### PR TITLE
[#1928] Login user automatically after creation

### PR DESCRIPTION
**Pull request by marienfressinaud**

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

**Comment by marienfressinaud** [comment]
Just realized that I could have updated the changelog as well! Let me know if you want me to do that

**Comment by Alkarex** [comment]
I typically write entries in the changelog outside pull request, as otherwise, it is too often causing merge conflicts

**Comment by Alkarex** [comment]
This seems to break the normal (admin) way to create new users:

image

**Comment by marienfressinaud** [comment]
You're right, just fixed it!

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/1928

**Pull request merged**
