### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by Alwaysin**

### CODE REVIEW

**Comment by Alwaysin** [comment]
Thanks Alkarex.

Also, not sure, but "Attention!" in english is not the same that in french, shouldn't we rename it to "Careful!"?

**Comment by Alkarex** [comment]
Indeed @Alwaysin, probably "Warning!"

**Comment by Alwaysin** [comment]
Hmm, I've also just noted that there is a mix between British and American English (_actualize_ -> en_US, _favourite_ -> en_GB).

Should we stick with EN_US, which seems to be the default for international communication? Or even provide two translations?

But maybe we should create a ticket about it.

**Comment by Alkarex** [comment]
Being in Europe, I use en_GB, but at some time we could have both, indeed.

**Pull request merged**
