### PR TITLE
Optimize images

### PR DESCRIPTION
**Pull request by andrewrabert**
Losslessly optimize images using [oxipng](https://github.com/shssoichiro/oxipng) (`oxipng --zopfli --opt max --strip all`)

Total size reduction: 502KB

### CODE REVIEW

**Comment by Alkarex** [comment]
Thanks @nvllsvm 
Good idea. I will check & merge just after the release of [FreshRSS 1.17.0](https://github.com/FreshRSS/FreshRSS/issues/3181) (tests welcome, by the way).

**Comment by aledeg** [comment]
@nvllsvm Could you add something in the developer documentation on that matter with the tools and the configuration you used ?

**Comment by Frenzie** [comment]
@aledeg I doubt it really does anything different than ye olde pngcrush or optipng[1] but it might indeed be good to document it.

[1] Besides being 0.1-0.3 times faster, but unless you run an image hosting site that's probably fairly irrelevant. ;-)

**Comment by aledeg** [comment]
@Frenzie My point is that if we have such entry in the documentation, we can point at it to contributors adding images in their PR. The tool itself is not important. What's important is to optimize images before submitting them.

**Comment by andrewrabert** [comment]
fwiw - here's a comparision optimizing a [3440x1440 image](https://cutewallpaper.org/21/3440x1440-space-wallpaper/Space-mod-3440x1440-WidescreenWallpaper.png).

**Note**: [image_optim](https://github.com/toy/image_optim) combines optipng, advpng, pngcrush, and a few others.

| Method                                | Time                                              | Size (Bytes) |
|---------------------------------------|---------------------------------------------------|--------------|
|  image_optim                        | 0.37s user 0.38s system 0% cpu 4:14.90 total      | 4161536      |
| original                              | n/a                                               | 5304320      |
| oxipng --opt max --strip all          | 37.22s user 0.30s system 1333% cpu 2.815 total    | 4354048      |
| oxipng --opt max --strip all --zopfli | 1686.02s user 0.94s system 490% cpu 5:43.96 total | 4100096      |

**Review by Alkarex — APPROVED** [review]

**Comment by Alkarex** [comment]
Thanks again @nvllsvm 👍  Please add a line for you in https://github.com/FreshRSS/FreshRSS/blob/master/CREDITS.md
Additional documentation welcome, if someone is motivated, maybe in https://github.com/FreshRSS/FreshRSS/tree/master/docs/en/developers

**Pull request merged**
