### PR TITLE
Add RSS Guard to list of software

### PR DESCRIPTION
**Pull request by martinrotter**
Closes #

Changes proposed in this pull request:

-
-
-

How to test the feature manually:

1.
2.
3.

Pull request checklist:

- [ ] clear commit messages
- [ ] code manually tested
- [ ] unit tests written (optional if too hard)
- [ ] documentation updated

[Additional information can be found in the documentation](https://github.com/FreshRSS/FreshRSS/tree/edge/docs/en/developers/04_Pull_requests.md).

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
lgtm

**Comment by aledeg** [comment]
Thank you for your contribution.
Next time you open a PR, please add some information in the template to know what we are looking for. I had to check the commit message and the modification in the file to understand what this was about.
Fortunately, that was not hard to figure things out but it will help us. Thank you!

**Comment by Alkarex** [comment]
We should update https://github.com/FreshRSS/FreshRSS/blob/edge/README.fr.md as well

**Comment by aledeg** [comment]
@martinrotter Do you mind adding another PR for the file mentioned by @Alkarex? Thank you!

**Comment by Alkarex** [comment]
@martinrotter I have just tried RSS Guard 3.9.2 on Windows, and the login request `/accounts/ClientLogin` does not seem to work. For this request, FreshRSS accepts either HTTP GET or standard POST (i.e. with Content-Type *application/x-www-form-urlencoded* or *multipart/form-data*). However, it looks like there is no `Content-Type` header in the RSS Guard request, making it fail.

**Comment by martinrotter** [comment]
> 
> 
> @martinrotter I have just tried RSS Guard 3.9.2 on Windows, and the login request `/accounts/ClientLogin` does not seem to work. For this request, FreshRSS accepts either HTTP GET or standard POST (i.e. with Content-Type _application/x-www-form-urlencoded_ or _multipart/form-data_). However, it looks like there is no `Content-Type` header in the RSS Guard request, making it fail.

Will look into it right now, but for me my testing docker FreshRSS instance works.

**Comment by martinrotter** [comment]
> 
> 
> @martinrotter I have just tried RSS Guard 3.9.2 on Windows, and the login request `/accounts/ClientLogin` does not seem to work. For this request, FreshRSS accepts either HTTP GET or standard POST (i.e. with Content-Type _application/x-www-form-urlencoded_ or _multipart/form-data_). However, it looks like there is no `Content-Type` header in the RSS Guard request, making it fail.

image

I got warning "content-type missing in HTTP POST, defaulting to application/x-www-form-urlencoded. Use QNetworkRequest::setHeader() to fix this problem.", will fix.

**Comment by martinrotter** [comment]
OK, it is fixed with https://github.com/martinrotter/rssguard/commit/9beb4dda8af667388d6ffd2535de639d2f532e63.

Development build will be visible in 15 minutes [here](https://github.com/martinrotter/rssguard/releases/tag/devbuild). Can you test, @Alkarex?

**Pull request merged**
