### PR TITLE
Add a docker compose example.

### PR DESCRIPTION
**Pull request by upils**
Using postgresql and with traefik specific labels.

### CODE REVIEW

**Comment by Alkarex** [comment]
Thanks @upils , that looks good.
Could you please consider adding a little sub-section in https://github.com/FreshRSS/FreshRSS/blob/dev/Docker/README.md , under *Deployment in production*, briefly explaining what parts of the  docker-compose file to edit, and how to launch it afterwards?

**Comment by upils** [comment]
Yeah, sure !

**Comment by Alkarex** [comment]
Great @upils 👍 
Could you please move the new section at the end, so that is becomes a sub-section under *Deployment in production* ?

**Comment by Alkarex** [comment]
Merged. Thanks again :-)

**Pull request merged**
