### PR TITLE
fix active check in subscription menu

### PR DESCRIPTION
**Pull request by kevinpapst**
The active check misbehaved: 
when selecting the "Subscription tools" link, the "Subscriptions management" link was highlighted.

### CODE REVIEW

**Comment by Frenzie** [comment]
Ah, it took me like five seconds to understand where the problem even was but luckily there was the HTML. :-P

screenshot_2018-04-01_15-14-41

**Comment by kevinpapst** [comment]
Ha, sorry for the confusion - I am using the german version and mistranslated the links in my original post (edited and now using the correct ones from your screenshot),

**Comment by Alkarex** [comment]
Minor syntax changes https://github.com/FreshRSS/FreshRSS/pull/1858/commits/8528b4d0fb3a01b7eeb32f30b132b781218c1ffd

**Comment by kevinpapst** [comment]
Any objections?

**Comment by Frenzie** [comment]
I'll take the syntax update as implicit approval. ;-)

**Pull request merged**
