### PR TITLE
Update the Movim share URL

### PR DESCRIPTION
**Pull request by edhelas**
Just a little fix to make FreshRSS working again with the new Movim urls

### CODE REVIEW

**Comment by aledeg** [comment]
Thanks

**Comment by aledeg** [comment]
I merged the PR but I didn't notice it was on beta. I reverted it.
Could you resubmit it on dev branch?

**Comment by Alkarex** [comment]
@aledeg Try to make a git reset [commit-id] instead of making an additional commit

And when it is on the wrong branch, it is possible to cherry-pick it

**Comment by aledeg** [comment]
Sure. Can I do that on github interface? Or should I do it on my machine?

**Comment by Alkarex** [comment]
@aledeg Yes, from your own machine. I have just done it, noting the steps:

``` sh
git checkout beta
git pull
git log
# Find the last valid commit ID (can also be seen from Github)
git reset --hard 919c9c83013ea310f01c309f00dea3f8afa9033e
git push -f
```

**Comment by Alkarex** [comment]
Please check the cherry-pick https://github.com/FreshRSS/FreshRSS/commit/a90f6ad8407d5bfda66b7299124cf82f54153736

**Pull request merged**
