### PR TITLE
Upgrade PHPMailer to 6.3.0

### LINKED ISSUE #3456: Update PHPMailer to 6.2.0
It's been several months since PHPMailer was last upgraded. The latest release 6.2.0 ensures PHP 8.0 support for tests and is the latest and greatest. I'll work on getting a PR for this version.

### PR DESCRIPTION
**Pull request by BrookeDot**
Closes #3456

Changes proposed in this pull request:

- Upgraded PHPMailer to 6.3.0. 

--- 

Since the last upgrade to 6.1.6 the following changes have been made upstream:

Commit history upstream:
https://github.com/PHPMailer/PHPMailer/compare/v6.1.6...v6.3.0

**PHPMailer 6.1.7**

-  Split SMTP connection into two separate methods
-   Undo BC break in PHP vesions 5.2.3 - 7.0.0 introduced in 6.1.2 when injecting callables for address validation and HTML to text conversion
-  Save response to SMTP welcome banner as other responses are saved
-  Retry stream_select if interrupted by a signal

**PHPMailer 6.1.8**
-  Mark ext-hash as required in composer.json. This has long been required, but now it will cause an error at install time rather than runtime, making it easier to diagnose
-  Make file upload examples safer
-  Update links to SMTP testing servers
-  Avoid errors when set_time_limit is disabled (you need better hosting!)
-  Allow overriding auth settings for local tests; makes it easy to run tests using HELO
-  Recover gracefully from errors during keepalive sessions
-  Add AVIF MIME type mapping
-  Prevent duplicate To headers in BCC-only messages when using mail()
-  Avoid file function problems when attaching files from Windows UNC paths
-  Improve German, Bahasa Indonesian, Filipino translations
-  Add Javascript-based example
-  Increased test coverage

**PHPMailer 6.2.0**

-  PHP 8.0 compatibility
-  Switch from PHP CS Fixer to PHP CodeSniffer for coding standards
-  Create class constants for the debug levels in the POP3 class
-  Improve French, Slovenian, and Ukrainian translations
-  Improve file upload examples so file extensions are retained
-  Resolve PHP 8 line break issues due to a very old PHP bug being fixed
-  Avoid warnings when using old openssl functions
-  Improve Travis-CI build configuration

**PHPMailer 6.3.0**

- Handle early connection errors such as 421 during connection and EHLO states
-  Switch to Github Actions for CI
-  Generate debug output for mail(), sendmail, and qmail transports. Enable using the same mechanism as for SMTP: set SMTPDebug > 0
-  Make the mail() and sendmail transports set the envelope sender the same way as SMTP does, i.e. use whatever From is set to, only falling back to the sendmail_from php.ini setting if From is unset. This avoids errors from the mail() function if Sender is not set explicitly and php.ini is not configured. This is a minor functionality change, so bumps the minor version number.
-  Extend parseAddresses to decode encoded names, improve tests

--- 

The minimum PHP requirement did not change. 

How to test the feature manually:

1.  Checkout this Branch
2.  Setup SMTP in data/config.php
3.  Test email sending such as by sharing an article

Pull request checklist:

- [x] clear commit messages
- [ ] code manually tested
- [ ] unit tests written (optional if too hard)
- [x] documentation updated (Not required)

### CODE REVIEW

**Comment by BrookeDot** [comment]
I don't know why, but I had a feeling this would happen. PHPMailer 6.3.0 was just released. I'll refresh this patch:
https://github.com/PHPMailer/PHPMailer/releases/tag/v6.3.0

**Comment by marienfressinaud** [comment]
Thanks @BrookeDot, looks ok to me :)

**Review by marienfressinaud — APPROVED** [review]

**Comment by marienfressinaud** [comment]
@Alkarex I can't remember how the ci/dockercloud check is configured, nor why it's so long :s (I'm merging now since the changes in this PR have no impact on the Dockerfile)

**Comment by Frenzie** [comment]
@marienfressinaud I don't think it does much of anything other than building the images? I'm guessing there's a queue.

**Pull request merged**
