### PR TITLE
Google Reader API: work-around for News+ bug

### PR DESCRIPTION
**Pull request by Alkarex**
https://github.com/noinnion/newsplus/issues/84#issuecomment-57834632
https://github.com/FreshRSS/FreshRSS/issues/443
Copy from @jochenberger https://github.com/noinnion/newsplus/issues/84#issuecomment-57600231

> Imagine there is 1 unread item (let's call it A) in tt-rss and that is synced to News+ correctly, so News+ shows A as unread too.
> Then, I read the item A in tt-rss, so there are no unread items left. Then, I start the sync in News+ again. A is _not_ marked as read in News+.
> If, _however_, a new item B arrives in tt-rss (so there is a new unread item again) and I start the sync in News+, B is fetched and A is marked as unread, leaving only B as unread.

### CODE REVIEW

**Comment by Alkarex** [comment]
@Alwaysin Here is a patch for a little bug that should have your interest if you are still using News+ for the mobile client.

**Comment by Alwaysin** [comment]
Yes I'm still using it!
Awesome patch which looks really simple, but it's so good to have it! Thanks :D

**Comment by Alkarex** [comment]
Please let me know the results, if you test this patch, @Alwaysin , so that it may be included in the upcoming beta 1.1.1.

**Comment by Alwaysin** [comment]
Just tested, it works fine!

**Pull request merged**
