### PR TITLE
Update zh-cn Translation

### PR DESCRIPTION
**Pull request by myuki**

### CODE REVIEW

**Comment by myuki** [comment]
I don't understand what the `fetching the article content` which in `Content action when fetching the article content` exactly behavior. Is that mean fetching the article new updated content?

**Comment by aledeg** [comment]
@Myuki Thank you for your contribution.

I'll try to answer your question regarding the fetched content.
You know some feeds only include a partial view of the article. That's what the CSS fetching feature is for. It takes the article address and try to locate the full content of the article using a CSS selector. Once done, there are 3 options:

1. Replace the feed content (partial) with the CSS selector content (complete).
1. Add the CSS selector content before the feed content.
1. Add the CSS selector content after the feed content.

The 2 last options are needed when the feed content is not really a partial view of the article and you want to keep the 2.

I hope this make sense. If not, I'll be happy to help.

**Review by aledeg — APPROVED** [review]

**Comment by myuki** [comment]
> 
> 
> @Myuki Thank you for your contribution.
> 
> I'll try to answer your question regarding the fetched content.
> You know some feeds only include a partial view of the article. That's what the CSS fetching feature is for. It takes the article address and try to locate the full content of the article using a CSS selector. Once done, there are 3 options:
> 
>     1. Replace the feed content (partial) with the CSS selector content (complete).
> 
>     2. Add the CSS selector content before the feed content.
> 
>     3. Add the CSS selector content after the feed content.
> 
> 
> The 2 last options are needed when the feed content is not really a partial view of the article and you want to keep the 2.
> 
> I hope this make sense. If not, I'll be happy to help.

Thanks, I understood what CSS fetching doing. I should change some translation about fetching.

**Comment by aledeg** [comment]
@Myuki Quick follow up. Are you satisfied with the translation in that PR? Can we merge that or do you need more time?
Thank you!

**Comment by myuki** [comment]
> @Myuki Quick follow up. Are you satisfied with the translation in that PR? Can we merge that or do you need more time?
> Thank you!

I think it's good enough for this PR. If need some change I will create a new PR.

**Pull request merged**
