### PR TITLE
Release 1.3.2-beta

### PR DESCRIPTION
**Pull request by Alkarex**
https://github.com/FreshRSS/FreshRSS/milestones/1.3.2-beta

### CODE REVIEW

**Comment by Alkarex** [comment]
@marienfressinaud @aledeg I will merge the current /dev in /beta for 1.3.2-beta in a few hours. Let me know if you have any comment. See changelog :-)
/dev has been quite stable, has corrected a few important bugs (e.g. MySQL 5.7+) and I am about to make new changes to /dev which will require testing (so it is good to release a beta before that).

**Comment by aledeg** [comment]
@Alkarex Is it pushed already on the deployment server?

**Comment by Alkarex** [comment]
@aledeg No, only here for updates by git, or manually. Marien is in holidays :-)

**Comment by aledeg** [comment]
@Alkarex I see. I'll do that at home!
Anyway, good job on maintaining the project. I've been away for a while now.

**Comment by marienfressinaud** [comment]
Fixed :)

**Pull request merged**
