### PR TITLE
Statistics: improved layout

### PR DESCRIPTION
**Pull request by math-GH**
Changes proposed in this pull request:
- with a grid layout the general layout is improved
- mobile layout improved

before: no mobile layout (2 tables in 1 row)
grafik

fixed: in mobile layout each table in 1 row
grafik

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested

### CODE REVIEW

**Comment by math-GH** [comment]
Same in Articles repartition. I fixed it too

**Review by aledeg — COMMENTED** [review]
good job!

**Review by aledeg — APPROVED** [review]

**Review by Frenzie — APPROVED** [review]
CSS in 2021 does offer some advantages. :-)

**Comment by Alkarex** [comment]
Would it be possible to do something to be more fluid, or with some constrains, to work better when resizing the window (avoid overlaps at least)?
image

**Comment by math-GH** [comment]
@Alkarex : The images/canvas are created via JavaScript after the page loaded. I did not dive into that.
It is an edge case to resize the page while reading it (to watch the stats itself is also an edge case).

It is Flotr2 used to create the canvas images. Flotr2 itself is not maintained anymore (last commit in 2014 https://github.com/HumbleSoftware/Flotr2). I do not want to touch/change it

**Comment by math-GH** [comment]
fixed it with scrolling bars

grafik

**Pull request merged**
