### PR TITLE
Option to force clear cache

### PR DESCRIPTION
**Pull request by Alkarex**
https://github.com/FreshRSS/FreshRSS/issues/1020#issuecomment-428515868
image

### CODE REVIEW

**Comment by Alkarex** [comment]
@spackmat Seems to work fine for https://www.shopblogger.de/blog/feeds/index.rss2

**Comment by spackmat** [comment]
I'll try and observe all my feeds. Big thanks!

**Comment by Alkarex** [comment]
@spackmat I am guessing you might speak German - if yes, maybe you could consider submitting the German translation of *Always clear cache* :-)

https://github.com/FreshRSS/FreshRSS/blob/0aecf442946f7aa618fcc759f79807cd81346dc4/app/i18n/de/sub.php#L30

**Comment by spackmat** [comment]
Yes, this would be "Cache immer leeren", if directly translated and "Nicht cachen (für defekte Feeds)" for "Don't cache (for defective feeds)".

**Comment by Alkarex** [comment]
@spackmat I like your second proposition 👍  Could you please put it in https://github.com/FreshRSS/FreshRSS/blob/dev/app/i18n/de/sub.php ? (the easiest is just to use the online edit button)

**Comment by spackmat** [comment]
I don't have write access, so I forked and sent a pull request.

**Comment by spackmat** [comment]
I don't have write access, so I forked and sent a pull request.

**Comment by spackmat** [comment]
I don't have write access, so I forked and sent a pull request.

**Comment by spackmat** [comment]
I don't have write access, so I forked and sent a pull request.

**Comment by spackmat** [comment]
I don't have write access to the Repository, so I forked and sent a pull request. (Two times, as GitHub shows me errors at the moment).

**Comment by spackmat** [comment]
I don't have write access to the Repository, so I forked and sent a pull request. (Two times, as GitHub shows me errors at the moment).

**Comment by spackmat** [comment]
I don't have write access to the Repository, so I forked and sent a pull request. (Two times, as GitHub shows me errors at the moment).

**Pull request merged**
