### PR TITLE
jQuery 3.4.1

### PR DESCRIPTION
**Pull request by Alkarex**
Only used for statistics graphs

### CODE REVIEW

**Comment by aledeg** [comment]
I don't know if those stats are making any sense. Should we keep them?

**Comment by Frenzie** [comment]
They're pretty cool though. :-)

**Comment by Alkarex** [comment]
Although they are pretty slow to generate, and could be better, I do look at them once in a while personally, and back when the feature was added, there were positive responses

**Comment by aledeg** [comment]
I am just asking :) I never use them even though I wrote the whole thing.

**Pull request merged**
