### PR TITLE
Prepare release of version 1.8.0

### PR DESCRIPTION
**Pull request by Alkarex**
https://github.com/FreshRSS/FreshRSS/milestone/24

### CODE REVIEW

**Comment by Alkarex** [comment]
This release is long due, with several important bug fixes. It was initially planned to be a minor release 1.7.1, but since we have had a lot of code changed for Travis, and a change of minimal PHP version, I think it is better to go for 1.8.0.

Changelog: https://github.com/FreshRSS/FreshRSS/blob/dev/CHANGELOG.md

* Compatibility:
	* Minimal PHP version increased to PHP 5.3.8+ to fix sanitize bug [#1604](https://github.com/FreshRSS/FreshRSS/issues/1604)
	* Add support for PHP 7.1 in the API [#1584](https://github.com/FreshRSS/FreshRSS/issues/1584), [#1594](https://github.com/FreshRSS/FreshRSS/pull/1594)
* UI
	* New page for subscription tools [#1534](https://github.com/FreshRSS/FreshRSS/issues/1354)
	* Adjustments to the padding of the tree of categories and feeds [1589](https://github.com/FreshRSS/FreshRSS/pull/1589)
	* Fix feed column position after lazy-loading images [#1616](https://github.com/FreshRSS/FreshRSS/pull/1616)
	* Force UI controls for HTML5 video and audio [#1642](https://github.com/FreshRSS/FreshRSS/pull/1642)
	* Fix share menu on small screens [#1645](https://github.com/FreshRSS/FreshRSS/pull/1645)
	* Go back to previous view when collapsing article [#1177](https://github.com/FreshRSS/FreshRSS/issues/1177)
* CLI
	* New command `./cli/update-user` to update user settings [#1600](https://github.com/FreshRSS/FreshRSS/issues/1600)
* I18n
	* Korean [#1578](https://github.com/FreshRSS/FreshRSS/pull/1578)
	* Portuguese (Brazilian) [#1648](https://github.com/FreshRSS/FreshRSS/pull/1648)
	* Fix month abbreviations [#1560](https://github.com/FreshRSS/FreshRSS/issues/1560)
* Bug fixing
	* Fix API compatibility bug between PostgreSQL and EasyRSS [#1603](https://github.com/FreshRSS/FreshRSS/pull/1603)
	* Fix PostgreSQL error when adding entries with duplicated GUID [#1610](https://github.com/FreshRSS/FreshRSS/issues/1610), [#1614](https://github.com/FreshRSS/FreshRSS/issues/1614)
	* Fix for RSS feeds containing HTML in author field [#1590](https://github.com/FreshRSS/FreshRSS/issues/1590)
	* Fix logout issue in global view due to CSRF [#1591](https://github.com/FreshRSS/FreshRSS/issues/1591)
* Misc.
	* Travis continuous integration [#1619](https://github.com/FreshRSS/FreshRSS/pull/1619)
	* Allow longer database usernames [#1597](https://github.com/FreshRSS/FreshRSS/issues/1597)

Thanks to all contributors: @aledeg @marienfressinaud @Frenzie @Alwaysin @gsongsong @romibi @sandfoxme @Trim @rcutanda @araujo0205 ...

If you have a chance to give a try to the /dev version before tomorrow evening, please post some feedback here :-) 

@GeoZzNL @redinsight @giorgiobeggiora @geekafy @oupala @NerosTie @mathieumd @subic @auricom  ...

**Comment by araujo0205** [comment]
I tested it and everything is working.
The language is Portuguese (Brazil) not Portuguese (Brazilian). Brazilian is the capital of Brazil :)

**Comment by Frenzie** [comment]
Seems fine to me. 👍 

@araujo0205 It's Brazilian (the adjective) Portuguese. Whether it's right or wrong depends on whether you want to write `Dutch (Belgian)`/`German (Austrian)`/`Portuguese (Brazilian)` or `Dutch (Belgium)`/`German (Austria)`/`Portuguese (Brazil)`. I think it's completely arbitrary, but in the language dropdown list the system should be internally consistent. :-)

**Comment by Alkarex** [comment]
Thanks for the feedback @araujo0205 and @Frenzie 👍 
For the record, the capital of Brazil is [Brasília](https://en.wikipedia.org/wiki/Bras%C3%ADlia) without 'n' :-)

**Comment by aledeg** [comment]
I didn't tested it thoroughly but so far it looks good to me.

**Comment by araujo0205** [comment]
Thanks @Alkarex and @Frenzie . The internationalization is new for me.
I thought there was change depending on the language. Like Brazil and Brazil :)

**Comment by NerosTie** [comment]
Still no new update available in my freshrss, is it normal?

**Comment by aledeg** [comment]
Yes. See [here](https://github.com/FreshRSS/update.freshrss.org/issues/3)

**Comment by marienfressinaud** [comment]
Update should be ok now :)

**Pull request merged**
