### PR TITLE
Add a request method to extract arrays

### PR DESCRIPTION
**Pull request by aledeg**
Changes proposed in this pull request:

- Add a request method to extract arrays

How to test the feature manually:

1. add a request param with new lines and use the new method to parse it.
2. this will produce an array of string where each string is one of the line

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested
- [ ] unit tests written (optional if too hard)
- [ ] documentation updated

[Additional information can be found in the documentation](https://github.com/FreshRSS/FreshRSS/tree/edge/docs/en/developers/04_Pull_requests.md).

### CODE REVIEW

**Comment by Alkarex** [comment]
I have not understood the type of expected request. Can you please provide an example?

**Comment by aledeg** [comment]
Sure.
The goal of that method is to convert the content of a textarea into an array where each cell is one line of the textarea. My thoughts were to use that in the whitelist extension mentioned in #3622. It might be useful also for the feed filters.
Let me know if my explanation helps or if you need more information to understand what I have in mind.

**Comment by Alkarex** [comment]
Ok. I was a bit confused because I thought it was an helper for array query params https://php.net/faq.html#faq.html.arrays
Maybe change the name to `paramLines` or something like that?

**Comment by aledeg** [comment]
I understand. I'll find a different name!

**Comment by aledeg** [comment]
@Alkarex I've made some changes and I've added some comments in the code.

**Pull request merged**
