### PR TITLE
CLI: Command-Line Interface

### PR DESCRIPTION
**Pull request by Alkarex**
https://github.com/FreshRSS/FreshRSS/issues/1095
https://github.com/FreshRSS/FreshRSS/issues/833

### CODE REVIEW

**Comment by Alkarex** [comment]
Usage:

``` sh
./cli/do-install.php --default_user admin --auth_type form  ( --environment production --base_url https://rss.example.net/ --language en --title FreshRSS --allow_anonymous --api_enabled --db-type mysql --db-host localhost:3306 --db-user freshrss --db-password dbPassword123 --db-base freshrss --db-prefix freshrss )
# Does not create the default user. Do that with ./cli/create-user.php

./cli/create-user.php --user username ( --password 'password' --api-password 'api_password' --language en --email user@example.net --token 'longRandomString' --no-default-feeds )

./cli/list-users.php
# Return a list of users, with the default/admin user first

./cli/actualize-user.php --user username

./cli/delete-user.php --user username

./cli/import-for-user.php --user username --filename /path/to/file.ext

./cli/export-opml-for-user.php --user username > /path/to/file.opml.xml

./cli/export-zip-for-user.php --user username ( --max-feed-entries 100 ) > /path/to/file.zip
```

**Comment by Alkarex** [comment]
@plopoyop @oupala @ingelres @Jucgshu Comments welcome for this draft of Command Line Interface for FreshRSS

**Comment by lapineige** [comment]
A tough from this issue #1342 :

I just saw that the new CLI can be really handy to make some (automated) backups on a regular base: https://github.com/FreshRSS/FreshRSS/pull/1338

Thanks to this command: `./cli/export-opml-for-user.php --user username > /path/to/file.opml.xml`
(question: what's the difference with `export-zip` ?)
Actually I'm doing backups by making a copy of all the files, but I could improve it by exporting the feeds thanks to this CLI, and also backup the settings, and the status of the feeds (to save the unread list for instance). edit: I forgot the zip include the feeds content
Do you think that would be a good addition, as an extension to automate it, or if I should just document the cron tasks I'll use ?

**Comment by Alkarex** [comment]
@lapineige `export-zip.php` exports a ZIP with an OPML, favourites, and feeds content.
For your full back-up, you could just dump your database https://github.com/FreshRSS/FreshRSS/tree/dev#backup
I do not think it makes sense to have an extension for that. Just a better documentation. If anything, I am considering making an additional CLI to export/import to SQLite, to ease a migration between different databases or systems.

**Comment by lapineige** [comment]
> @lapineige export-zip.php exports a ZIP with an OPML, favourites, and feeds content.

Sorry I made a confusion, I forgot that I'm doing this with a zip and not just the opml.

> For your full back-up, you could just dump your database https://github.com/FreshRSS/FreshRSS/tree/dev#backup

Ok thanks.

> I do not think it makes sense to have an extension for that. Just a better documentation. 

I do agree. Can I help here ?
I might include a cron task somewhere, in the doc' or in a tutorial, so people have it directly if they want to.
(even if it's very simple, you would not need to reinvent the wheel)

> If anything, I am considering making an additional CLI to export/import to SQLite, to ease a migration between different databases or systems.

I do not have such needs (well, I'm not planning to stop using FreshRSS :smiley:), but it can be an option if someone raise this need someday.

**Comment by Alkarex** [comment]
I meant to migrate between MySQL <-> SQLite <-> PostgreSQL :-)
Yes, your help would indeed be greatly appreciated in the documentation https://github.com/FreshRSS/documentation 👍 
For instance, there is nothing on the CLI so far... If you have more energy, there is a number of things written in GitHub issues, which should be put in the documentation as well. E.g. the issues with a "documentation" tag https://github.com/FreshRSS/FreshRSS/issues?q=label%3ADocumentation

**Comment by Alkarex** [comment]
Targetting FreshRSS 1.6 for this week-end. Tests welcome https://github.com/FreshRSS/FreshRSS/issues/1328

**Comment by Jucgshu** [comment]
Tested both opml & zip export with cli. Works like a charm !

Awesome new feature !

**Comment by Alkarex** [comment]
Thanks for the tests!

**Comment by oupala** [comment]
I'm actively testing the cli feature in order to finalize the ansible playbook that could install FressRSS from A to Z.

See my first feedback in #1443.

**Pull request merged**
