### PR TITLE
FreshRSS 1.10.0

### PR DESCRIPTION
**Pull request by Alkarex**
Let's start testing /dev a bit more and complete the last few tasks: https://github.com/FreshRSS/FreshRSS/milestones/1.10.0
I have promised to the developer of [FeedMe](https://play.google.com/apps/testing/com.seazon.feedme) to release FreshRSS 1.10.0 soon :-P

There is a [nice little set of changes](https://github.com/FreshRSS/FreshRSS/blob/dev/CHANGELOG.md):

* API
	* Add compatibility with FeedMe 3.5.3+ on Android [#1774](https://github.com/FreshRSS/FreshRSS/pull/1774)
* Features
	* Ability to pause feeds, and to hide them from categories [#1750](https://github.com/FreshRSS/FreshRSS/pull/1750)
	* Ability for the admin to reset a user’s password [#960](https://github.com/FreshRSS/FreshRSS/issues/960)
* Security
	* Allow HTTP Auth login with `REDIRECT_REMOTE_USER` when using Apache internal redirect [#1772](https://github.com/FreshRSS/FreshRSS/pull/1772)
* UI
	* New icons for marking as favourite and marking as read in the Reading View [#603](https://github.com/FreshRSS/FreshRSS/issues/603)
	* Add shortcuts to switch views [#1755](https://github.com/FreshRSS/FreshRSS/pull/1755)
* Bug fixing
	* Fix login bug when HTTP `REMOTE_USER` changes (used by YunoHost) [#1756](https://github.com/FreshRSS/FreshRSS/pull/1756)
	* Fix warning in PHP 7.2 [#1739](https://github.com/FreshRSS/FreshRSS/pull/1739)
* Extensions
	* Allow extensions to define their own reading view [#1714](https://github.com/FreshRSS/FreshRSS/pull/1714)
* I18n
	* Updated Chinese [#1769](https://github.com/FreshRSS/FreshRSS/pull/1769)
	* Updated Korean [#1776](https://github.com/FreshRSS/FreshRSS/pull/1776)
* Misc.
	* More sites in `force-https.default.txt` [#1745](https://github.com/FreshRSS/FreshRSS/pull/1745)
	* Trim URLs when adding new feeds [#1778](https://github.com/FreshRSS/FreshRSS/pull/1778)

### CODE REVIEW

**Comment by marienfressinaud** [comment]
I'll prepare the update script in the next few days ;)

**Comment by Frenzie** [comment]
Alright, I'll start testing it this week. :-)

**Comment by Frenzie** [comment]
Hooray! :cake: 

I didn't encounter any issues over the past week or you would've heard about it. ;-)

**Comment by Frenzie** [comment]
Oh drat, I never used EasyRSS on my phone while testing. Author info is missing. I'll post a couple of screens later.

**Pull request merged**
