### PR TITLE
Change i18n process

### PR DESCRIPTION
**Pull request by aledeg**
Changes proposed in this pull request:

- Remove ignore folder and files
- Add translation state in the translation file

How to test the feature manually:

1. Manipulate translation

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested
- [ ] unit tests written (optional if too hard)
- [x] documentation updated

[Additional information can be found in the documentation](https://github.com/FreshRSS/FreshRSS/tree/edge/docs/en/developers/04_Pull_requests.md).

Before, the ignore info were stored in a different file which was a bit cumbersome
for new comers. Now, this info is stored directly in the translation file as a
comment.

Before, there was no way of telling translators that a previously translated string
was in need of a new translation. Now, the dirty information is there to convey that
info.

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
Sounds great! And looks sane to me in the CLI changes. :+1:

**Comment by Frenzie** [comment]
(Comment on the version from a few minutes ago. What changed? :-) )

**Comment by aledeg** [comment]
Thank you!
Fixing few errors to comply with the CI

**Comment by Alkarex** [comment]
Looks great 👍🏻

**Comment by aledeg** [comment]
Thank you!
I need to add some info in the documentation before it's ready to merge.

**Comment by Alkarex** [comment]
@aledeg if you have not seen it yet, you can try `make fix-all` and `make test-all` locally (though the requirements are not automatically done yet - help welcome -, so you first need to install `npm` and `composer` manually)

**Comment by aledeg** [comment]
@Alkarex Good to know. I'll try to keep that in mind.
I've updated the documentation. I think it is ready now.

**Comment by Alkarex** [comment]
As a quick test, `cli/manipulate.translation.php -a format` will add a `TODO` to a line that is identical to the English one (good), but not remove a `TODO` if the line is different (not so good). Is that expected, @aledeg ?
Just an idea: maybe a `TODO` on a line different from the English version could be modified to `DIRTY`

**Comment by aledeg** [comment]
It was not expected. Thank you for testing. I'll address that.

**Comment by aledeg** [comment]
It's fixed! Thank you for noticing.

**Pull request merged**
