### PR TITLE
SimplePie: decode special chars for MAYBE_HTML

### PR DESCRIPTION
**Pull request by Alkarex**
https://github.com/FreshRSS/FreshRSS/issues/754
Needs to check with many feeds to see if this does not introduce
incompatibilities with some valid feeds.

### CODE REVIEW

**Comment by Alkarex** [comment]
I have been using this patch and it seems to work fine :-)
Anybody would like more time to test? Otherwise I will merge during the week-end.

**Comment by aledeg** [comment]
Let me do it since we shouldn't merge our own commits :) 

See the
new rules for more info 

Le 2015-03-21 7:27, Alexandre Alapetite a
écrit : 

> I have been using this patch and it seems to work fine :-)
> 
> Anybody would like more time to test? Otherwise I will merge during the
> week-end. 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> [1].

## Links:

[1]
https://github.com/FreshRSS/FreshRSS/pull/813#issuecomment-84317854

**Comment by Alkarex** [comment]
I have just found an example of an RSS2 feed ([Clubic](http://com.clubic.feedsportal.com/c/33464/f/581983/index.rss)) with an escaped HTML character entity reference:

``` xml
<title>NVIDIA GeForce GTX Titan X : la plus rapide à 1 200 &amp;euro; ?</title>
```

The current patch only handles escaped numeric character references (e.g. `&amp;#160;`). I am considering extending it to the above case, but this has higher risk of unwanted side effect.

Edit: new version https://github.com/Alkarex/FreshRSS/commit/0e08b5ba56b2117e0f3d9bea6ae725295e8700d5

**Comment by aledeg** [comment]
So should we merge that now or should we wait? I haven't tested it and I probably won't have time to do it before weekend

**Comment by Alkarex** [comment]
@aledeg I am running with this patch on my instance, and so far everything is good with my ~200 feeds. It would be nice to get some feedback from more users.

**Comment by aledeg** [comment]
ok, I'll wait 'til we have more feedback

**Comment by Alkarex** [comment]
Actually, I was trying to say that it was good to merge to get more feedback. I doubt anybody will test a branch not merged in /dev.

**Comment by Alwaysin** [comment]
I haven't encountered any problems with my ~40 feeds.

**Comment by Alkarex** [comment]
Thanks for the feedback @Alwaysin; sounds good :-)

**Comment by Alkarex** [comment]
Reference to SimplePie's identical bug https://github.com/simplepie/simplepie/issues/350

**Comment by Alkarex** [comment]
https://github.com/simplepie/simplepie/pull/400

**Pull request merged**
