### PR TITLE
Better control of number of entries per page or RSS feed

### PR DESCRIPTION
**Pull request by Alkarex**
https://github.com/FreshRSS/FreshRSS/issues/1249
- Since X hours: `https://freshrss.example/i/?a=rss&hours=3`
- Explicit number: `https://freshrss.example/i/?a=rss&nb=10`
- Limited by `min_posts_per_rss` and `max_posts_per_rss` in user config

### CODE REVIEW

**Comment by Alkarex** [comment]
Related: https://github.com/FreshRSS/FreshRSS/issues/848

**Comment by ryancom16** [comment]
**Test**: Pass

**Limits Tested**:
-user/config.php
'since_hours_posts_per_rss'
'min_posts_per_rss'
'max_posts_per_rss'

-url:
&hours=#
&nb=#

**notes**:
Fantastic work, all the limits are working correctly. Limits in config.php override url parameters as expected. &hours is appended to the rss feed when it is generated. One thing of note, when both &hours and &nb are included in the url, hours overrides nb. This is not a problem because users should be using one or the other.

**Comment by ryancom16** [comment]
note: Existing users will have to submit a change to their config in the web UI in order for the parameters to bin included in config.php.

Future suggestions: Have these parameters configurable in the web UI.

**Comment by Alkarex** [comment]
Thanks for the feedback :-)
Merged in the /dev branch

**Comment by alexis-** [comment]
Hi. First, thanks and drum rolls for this excellent project.
I was looking for a solution to aggregate and archive RSS feeds when I found FreshRSS.

It is my understanding that the _hours_ parameters of the _a=rss_ module allows one set a time window, in hours, for RSS retrieval, and based on the entries **pubDate**.

After toying with `https://demo.freshrss.org/i/?a=rss&hours=240` I found that items from 2018 were displayed in response, which is obviously way past the 240h window.

Is it intended behavior, or a glitch ?

Thanks !

**Comment by Frenzie** [comment]
I would imagine it's retrieval time, unless you mean these items were actually retrieved in 2018.

**Comment by Alkarex** [comment]
@alexis- : Indeed, as @Frenzie writes, `hours` filters on the discovery date, not the publication date. If you would like to filter out articles based on their declared date (which is not reliable) you can use the search parameter using a pubdate filter, such as:

`https://freshrss.example.net/i/?a=rss&hours=240&search=pubdate:PT250h`

Please open a new issue if needed.

P.S.: Do keep `hours` in the query or a `date:` filter in the search query, as filtering only on `pubdate` is slow (not indexed).

**Comment by alexis-** [comment]
Excellent answer. That makes sense and I understand now.

**Pull request merged**
