### PR TITLE
Remove warning for CURLOPT_FOLLOWLOCATION with open_basedir

### PR DESCRIPTION
**Pull request by Alkarex**
For PHP 5.6.0- http://www.php.net/ChangeLog-5.php#5.6.0
https://bugs.php.net/bug.php?id=65646
https://github.com/FreshRSS/FreshRSS/pull/1733
https://github.com/FreshRSS/FreshRSS/pull/1657
https://github.com/FreshRSS/FreshRSS/issues/1655

### CODE REVIEW

**Comment by Alkarex** [comment]
I have just changed a bit my mind. Please check again, now with a `version_compare(PHP_VERSION, '5.6.0') >= 0` in order for newer versions of PHP to actually use `open_basedir` if they want without breaking cURL redirections.

**Comment by kevinpapst** [comment]
What about adding a lib_php-compatibility.php file to collect all the nasty little pieces of code? 
Currently its only that one, but I am pretty sure there are more hidden gems in other places.
But besides that the logic looks good. If PHP_VERSION is 5.6.0 or higher it will always get executed.
How do you know that it is fixed in 5.6.0? I only see that it was reported for 5.5.3.

**Comment by Alkarex** [comment]
> How do you know that it is fixed in 5.6.0?

From the changelog http://www.php.net/ChangeLog-5.php#5.6.0

**Comment by kevinpapst** [comment]
Hahaha, that was too easy.

**Comment by Frenzie** [comment]
Btw, with 5.3 and 5.4 severely EOL will we still be actively taking <5.5 into account going forward?

**Comment by Alkarex** [comment]
@Frenzie We are slowly dropping old PHP versions when there is a clear need. See e.g. the move to PHP 5.3.8+ in FreshRSS 1.8.0 https://github.com/FreshRSS/FreshRSS/pull/1618#issuecomment-323708633

I am checking the usage statistics https://w3techs.com/technologies/details/pl-php/all/all as well as the status for a few (conservative but popular) Linux distributions:
* https://distrowatch.com/table.php?distribution=ubuntu (LTS branches)
* https://distrowatch.com/table.php?distribution=debian
* https://distrowatch.com/table.php?distribution=centos

While those old PHP versions are EOL upstream, they are still actively maintained with security patches by the various distributions.

Finally, I also look at the status at some large Web hosting services such as http://90plan.ovh.net/infos/

Reference to an older discussion https://github.com/FreshRSS/FreshRSS/issues/789#issuecomment-73878076

For the record, I run currently run my FreshRSS on PHP 7.1.

**Comment by Frenzie** [comment]
I recently switched to 7.0 (from 5.6 which I'd been using for a few years) alongside upgrading from Jessie to Stretch. 

> While those old PHP versions are EOL upstream, they are still actively maintained with security patches by the various distributions.

* Debian Squeeze (6) LTS support ended in February 2016. That had 5.3.
* Debian Wheezy (7) is on 5.4, support for which will end in a few months (March 2018).
* Debian Jessie (8, now oldstable) is on 5.6.
* Debian Stretch (9, stable) is on 7.0.

Ubuntu's should be similar. That's actually part of why I brought it up. :-)

Now CentOS — yes, that one is generally quite remarkable in how long support lasts. Do they have an easy online packages browser like Debian?

**Pull request merged**
