### PR TITLE
Also check pdo_pgsql driver after successful installation

### LINKED ISSUE #1690: Check install don't see pdo_pgsql after a successful installation on postgreSQL
### Problem

After a successful installation on postgreSQL, system don't detect any PDO driver.

### How to reproduce

1. Use php with pdo_pgsql and pgsql extensions. No other one.
2. Install FreshRSS
3. Go to Administration > Vérification de l'installation
4. System say « Vous ne disposez pas de PDO ou d’un des drivers supportés (pdo_mysql, pdo_sqlite, pdo_pgsql). »

### PR DESCRIPTION
**Pull request by blankoworld**
This should fix #1690

### CODE REVIEW

**Review by aledeg — CHANGES_REQUESTED** [review]
The code is fine. The commits in the PR aren't. Could you modify your base so it has only your commit and not other people's commits.
Thanks.

**Comment by blankoworld** [comment]
Oh sorry, my bad. I will create again a new branch from dev and add changes into it.

**Comment by Frenzie** [comment]
@aledeg Have you used GitHub's new squash merge functionality yet? We can be more lenient with first-time contributors these days. ;-)

**Comment by aledeg** [comment]
@Frenzie I am doing that all day long :D
You're right but I think we should educate contributors to ease our work. I just hope I wasn't too hash.

**Pull request closed without merging**
