### PR TITLE
Docker follow-up

### PR DESCRIPTION
**Pull request by Alkarex**
https://github.com/FreshRSS/FreshRSS/pull/1813

### CODE REVIEW

**Comment by Alkarex** [comment]
An automatic build is already working on the dev branch. To test:
```sh
mkdir -p ./data/
sudo docker run -dit --restart unless-stopped --log-opt max-size=10m \
	-v $(pwd)/data:/var/www/FreshRSS/data -p 8080:80 \
	--name freshrss freshrss/freshrss:dev
```

* https://cloud.docker.com/app/freshrss/repository/docker/freshrss/freshrss
* https://hub.docker.com/r/freshrss/freshrss/

**Comment by perrinjerome** [comment]
@Alkarex I tried a bit and it seems working well.

For the records, to use mysql, it's something like:
```sh
docker run --name db -v mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=pass -e MYSQL_DATABASE=db -e MYSQL_USER=user -e MYSQL_PASSWORD=pass -d mysql
docker run -v $(pwd)/data:/var/www/FreshRSS/data -p 8080:80 --link db --name freshrss freshrss/freshrss:dev
```

and with postgres:
```
docker run --name db -v pgdata:/var/lib/postgresql/data -e POSTGRES_PASSWORD=pass -e POSTGRES_DB=db -e POSTGRES_USER=user -d postgres
docker run -v $(pwd)/data:/var/www/FreshRSS/data -p 8080:80 --link db --name freshrss freshrss/freshrss:dev
```

in both cases, in the Database configuration step of installation, using `db` as Host, `user` as Database username `pass` as Database password and `db` as database.

**Comment by Alkarex** [comment]
Thanks for testing @perrinjerome 👍 
I had only tested with SQLite so far, so I am glad you gave a spin to MySQL and PostgreSQL :-)

**Comment by Alkarex** [comment]
If someone knows how to provide a custom README to https://hub.docker.com/r/freshrss/freshrss/ without it being overridden at each automated build, let me know :-)
Relative links and pictures to GitHub are broken, and I would rather like to have more Docker-specific info there instead of FreshRSS's main README.

**Comment by Alkarex** [comment]
@marienfressinaud If you spot anything (feature or documentation) from https://github.com/FreshRSS/docker-freshrss or https://github.com/FreshRSS/docker-freshrss-production that is not already covered with the new image, let's try to address it

**Comment by Alkarex** [comment]
Damn, simplexml missing for OPML import :-( Patch coming...

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/1819

**Pull request merged**
