### PR TITLE
Fix keep state after favourites tags

### LINKED ISSUE #4124: [BUG] State filter kept since 1.19
**Describe the bug**
After 1.19 update, the state filter parameter is kept in URL

**To Reproduce**

1. go to main feed (not displaying already read items, no state param in URL)
2. go to favorites (displaying already read items, state=3 in URL)
3. go to main feed again (already read items are displayed, state=3 in URLà

**Expected behavior**
selected state should match configuration, already read items not displayed, as it was before update, as expected

**Screenshots**
no need

**Environment information (please complete the following information):**
- Device: PC
- OS: Win 10
- Browser: FF 95
- FreshRSS version: 1.19.1
- Database version: SQLite
- PHP version: 7.3
- Installation type: shared hosting

**Additional context**
.

### PR DESCRIPTION
**Pull request by Alkarex**
#fix https://github.com/FreshRSS/FreshRSS/issues/4124 regression

Related previous PRs:
* https://github.com/FreshRSS/FreshRSS/pull/2766
* https://github.com/FreshRSS/FreshRSS/pull/3472
* https://github.com/FreshRSS/FreshRSS/pull/3986

### CODE REVIEW

**Comment by Alkarex** [comment]
@math-GH Could you please give it a quick test? And let's release 1.19.2 after that, as we have several PRs waiting for 1.20 already :-)

**Comment by aurmil** [comment]
successfully tested on my own "real life" instance: 1.19.1 + PR changes 👍

**Comment by math-GH** [comment]
my settings:
grafik

It means:
In normal view the "show read button" is disabled. (no "state" parameter in URL).

Steps:
- enable the "show read button" (state=3)
- disable the "show read button" (state=2)
- go to favorites

In favorites now the "show read button" (state=3) is disabled (because of the parameter in URL), but I expected a enabled "show read button", because of my settings.

grafik

**Comment by Alkarex** [comment]
> In favorites now the "show read button" (state=3) is disabled (because of the parameter in URL), but I expected a enabled "show read button", because of my settings.

Thanks for the test. I would like to say that it is now working as per design: as soon as you make a manual change to the filters, the filters are kept between views, overruling the default view and the settings for favourites / labels.

Click on the FreshRSS logo to reset the filters (no state parameter in URL)

**Comment by math-GH** [comment]
ok, that sounds fine

**Pull request merged**
