### PR TITLE
fix: #2701 Fix look of authors

### LINKED ISSUE #2701: Article list  displayed with flicker
I recently instlaled FreshRSS via docker on my home server and reading via a mobile app (Reeder4 on iOS in this case) works fine, but when reading via the web interface, there is some nasty flickering and/or overlay issues going on. I tried with Firefox, Chrome & Vivaldi and with the Chrome-based browsers, there is heavy flickering, whereas with Firefox there are overly issues for the article list - each time while hovering the mouse over the article list.

FreshRSS version is 1.15.3, running via linuxserver/freshrss docker on Ubuntu 18.04. Browsers were the respective latest version on Windows-10. The theme was changed with no effects.

image

freshrss_flicker

### PR DESCRIPTION
**Pull request by marienfressinaud**
Closes #2701

Changes proposed in this pull request:

- Place "author" element in the "title" block of entries

This fix makes the authors part of the "title item", so it's not
considered as another block. This is not perfect since authors will
disappear on small screens, but we can discuss of putting titles on
multi-lines (see https://github.com/FreshRSS/FreshRSS/issues/2344).

How to test the feature manually:

1. Enable "author" display
2. Disable the multiline CSS fix :stuck_out_tongue: 
3. Check the author element is placed next to the title (and not under)

Capture d’écran de 2020-01-16 16-58-38

Capture d’écran - 2020-01-16 à 16 58 56

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested
- [ ] unit tests written (optional if too hard)
- [ ] documentation updated

[Additional information can be found in the documentation](https://github.com/FreshRSS/FreshRSS/tree/master/docs/en/developers/04_Pull_requests.md).

### CODE REVIEW

**Comment by Frenzie** [comment]
Could you also include before screenshots?

**Review by Frenzie — APPROVED** [review]
lgtm but I don't use the feature

**Comment by marienfressinaud** [comment]
Sure! The main issue was the "flickering" behavior (better illustrations are given in the original ticket)

Capture d’écran de 2020-01-16 17-11-48

Capture d’écran - 2020-01-16 à 17 12 01

**Comment by Frenzie** [comment]
The whitespace on the before seems a bit excessive. Is that on all themes? Makes the after look like more of an improvement than it is. :-P

**Comment by marienfressinaud** [comment]
Yes it was on all themes! I don't think it was intended but since I don't use this feature, I didn't notice

**Comment by triatic** [comment]
I'm not sure about this one, I prefer the Author being in the same position for every post when I'm skim-reading the feed list.

**Comment by marienfressinaud** [comment]
It surely can be improved, but the previous version was problematic and hard to fix. I'll let you open another ticket if you think of a better solution, but it will have to wait for https://github.com/FreshRSS/FreshRSS/issues/2344 to be finished.

**Pull request merged**
