### PR TITLE
Mobile: Show Subscription Management button

### PR DESCRIPTION
**Pull request by triatic**
Allows Subscription Management button to show on mobile fly-out menu.

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
I figure that's probably okay.

**Comment by marienfressinaud** [comment]
There are few things that still bug me. I took screenshots by simulating a small screen of 360x640 (it's pretty small but my main point is valid for longer screens)

We just need to add a small margin on top of the subscription button:

Capture d’écran - 2020-02-13 à 11 06 54

Here, the input is a bit too long (and it's not that easy to fix with current implementation of `.stick` class):

Capture d’écran - 2020-02-13 à 11 06 02

The worse is on this screen. It isn't good for screen width smaller than ~950px. It would require a lot more work and global redesign. It's something that I've been planning to do in the future but it's not in my priorities.

Capture d’écran - 2020-02-13 à 11 06 25

**Comment by triatic** [comment]
I've added some padding above the Subscription Management button as suggested.

I agree the Subscription Management area needs mobile optimisation but at least it's accessible now.

**Comment by Frenzie** [comment]
@marienfressinaud Also see what I wrote in https://github.com/FreshRSS/FreshRSS/issues/1876#issuecomment-449711602

**Comment by marienfressinaud** [comment]
Sorry, I didn't answer.

> I agree the Subscription Management area needs mobile optimisation but at least it's accessible now.

Sure, but I don't see the benefit if it's unusable. The panel looks broken like this :( Maybe I should complete your PR but it wasn't in my priority. I'll see if I can find some time in the next weeks to work on it, but I can't promise anything.

**Comment by Alkarex** [comment]
It has become better thanks to https://github.com/FreshRSS/FreshRSS/pull/2911 but we still need to improve the layout in the mobile view to make it usable.
@javerous If you feel like having a look here as well, it would be great :-)

**Comment by javerous** [comment]
@Alkarex I will, but remember I have very limited web development capability :s

For the side panel (subscription manager), it looks like a lost fight, no ? I mean, it would probably be better to load the side panel as a plain full page (and it's not that hard with FreshRSS, it's just a matter not to call the JavaScript side view loader). Sorry if it was already suggested ^^'

**Comment by Alkarex** [comment]
Yes indeed, it needs to be full-width I believe

**Comment by marienfressinaud** [comment]
@javerous I don't know if you're working on this, but I can work on it

**Comment by javerous** [comment]
@marienfressinaud No, I didn't have the time. You can go ahead.

**Comment by marienfressinaud** [comment]
I'm closing this PR in favour of #2938: it's easier to work on my own branch / PR, but it reuses your work @triatic.

**Pull request closed without merging**
