### PR TITLE
Adding new items to force-https.default.txt

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Alkarex** [comment]
Thanks! Please target the /dev branch instead (until the next release, I cannot do it from the GitHub interface as we can sometimes, because there has been one manual merge in /master)

**Review by aledeg — APPROVED** [review]

**Comment by ghost** [comment]
Ok, it is done.

**Comment by Alkarex** [comment]
Thanks for the various pull-requests, @RyDroid :-)
Would you like to add you name to https://github.com/FreshRSS/FreshRSS/blob/dev/CREDITS.md ? That would be good.

**Comment by ghost** [comment]
Thank you for this free/libre software.
It was just tiny contributions, but I have (of course) no problem to be added to credits if you want to. If you do, my website is http://www.nicola-spanti.info/

**Comment by Alkarex** [comment]
All contributions matter :-)
Here you are https://github.com/FreshRSS/FreshRSS/commit/caccf8a970afa237cc44b49042c1a80b2158b2f6

**Comment by ghost** [comment]
Ok, thanks. :-)

**Pull request merged**
