### PR TITLE
FreshRSS 1.15

### PR DESCRIPTION
**Pull request by Alkarex**
Hi fellow FreshRSS users!
After 3 months of quite intense development, the next [version 1.15 of FreshRSS](https://github.com/FreshRSS/FreshRSS/milestones/1.15.0) is finally ready for testing before release.

Several big new features this time, and even more under the hood.

In particular, it is now possible to export/import any FreshRSS account to/from a SQLite file. This also allows you to migrate database (e.g. from MySQL to PostgreSQL) easily, and do better backups or migration from one server to another. Please try it and report whether that works well for you.

The archiving strategy has been reworked and now offers the possibility to control a maximum number of articles per feed. Archiving settings (which are always applied at feed level) can be define for each feed, or by category, or globally. A few additional rules are hidden (for instance always keep the articles seen at the last feed refresh). Dates are to be understood as when an article has last been seen in the original RSS feed, not the publication date. Give it a shot!

Our iOS users have one more client to choose from (the first implementing the Google Reader API, which is more powerful than the clients using the Fever API), and a lot more, see below.

Thanks to the 19 contributors who made this new version :-)

Full [changelog](https://github.com/FreshRSS/FreshRSS/blob/dev/CHANGELOG.md):
* CLI
	* Command line to export/import any database to/from SQLite [#2496](https://github.com/FreshRSS/FreshRSS/pull/2496)
* Features
	* New archiving method, including maximum number of articles per feed, and settings at feed, category, global levels [#2335](https://github.com/FreshRSS/FreshRSS/pull/2335)
	* New option to control category sort order [#2592](https://github.com/FreshRSS/FreshRSS/pull/2592)
	* New option to display article authors underneath the article title [#2487](https://github.com/FreshRSS/FreshRSS/pull/2487)
	* Add e-mail capability [#2476](https://github.com/FreshRSS/FreshRSS/pull/2476), [#2481](https://github.com/FreshRSS/FreshRSS/pull/2481)
	* Ability to define default user settings in `data/config-user.custom.php` [#2490](https://github.com/FreshRSS/FreshRSS/pull/2490)
		* Including default feeds [#2515](https://github.com/FreshRSS/FreshRSS/pull/2515)
	* Allow recreating users if they still exist in database [#2555](https://github.com/FreshRSS/FreshRSS/pull/2555)
	* Add optional database connection URI parameters [#2549](https://github.com/FreshRSS/FreshRSS/issues/2549), [#2559](https://github.com/FreshRSS/FreshRSS/pull/2559)
	* Allow longer articles with MySQL / MariaDB (up to 16MB compressed instead of 64kB) [#2448](https://github.com/FreshRSS/FreshRSS/issues/2448)
	* Add support for terms of service [#2520](https://github.com/FreshRSS/FreshRSS/pull/2520)
	* Add sharing with [Lemmy](https://github.com/dessalines/lemmy) [#2510](https://github.com/FreshRSS/FreshRSS/pull/2510)
* API
	* Add support for [Reeder-4](https://www.reederapp.com/) client [#2513](https://github.com/FreshRSS/FreshRSS/issues/2513)
* Compatibility
	* Require at least PHP 5.6+ [#2495](https://github.com/FreshRSS/FreshRSS/pull/2495), [#2527](https://github.com/FreshRSS/FreshRSS/pull/2527), [#2585](https://github.com/FreshRSS/FreshRSS/pull/2585)
	* Require `php-json` and remove remove `JSON.php` fallback [#2528](https://github.com/FreshRSS/FreshRSS/pull/2528)
	* Require at least PostgreSQL 9.5+ [#2554](https://github.com/FreshRSS/FreshRSS/pull/2554)
* Deployment
	* Take advantage of `mod_authz_core` instead of `mod_access_compat` when running on Apache 2.4+ [#2461](https://github.com/FreshRSS/FreshRSS/pull/2461)
	* Docker: Ubuntu image updated to 19.10 with PHP 7.3.8 and Apache 2.4.41 [#2577](https://github.com/FreshRSS/FreshRSS/pull/2577)
	* Docker: Alpine image updated to 3.10 with PHP 7.3.11 and Apache 2.4.41 [#2238](https://github.com/FreshRSS/FreshRSS/pull/2238)
	* Docker: Increase default PHP POST/upload size to ease importing ZIP files [#2563](https://github.com/FreshRSS/FreshRSS/pull/2563)
	* New environment variable `COPY_LOG_TO_SYSLOG` to see all logs at once in e.g. `docker logs -f` [#2591](https://github.com/FreshRSS/FreshRSS/pull/2591)
	* New environment variable `FRESHRSS_ENV` to control Minz development mode [#2508](https://github.com/FreshRSS/FreshRSS/pull/2508)
	* Git ignore `themes/xTheme-*` [#2511](https://github.com/FreshRSS/FreshRSS/pull/2511)
* Bug fixing
	* Fix missing PHP `opcache` package in Docker Alpine [#2498](https://github.com/FreshRSS/FreshRSS/pull/2498)
	* Fix IE11 / Edge keyboard compatibility [#2507](https://github.com/FreshRSS/FreshRSS/pull/2507)
	* Use `<dc:creator>` instead of `<author>` for RSS 2.0 outputs [#2542](https://github.com/FreshRSS/FreshRSS/pull/2542)
	* Fix PostgreSQL and SQLite database size estimation [#2562](https://github.com/FreshRSS/FreshRSS/pull/2562)
	* Fix broken SVG icons in Swage theme [#2568](https://github.com/FreshRSS/FreshRSS/issues/2568), [#2571](https://github.com/FreshRSS/FreshRSS/pull/2571)
* Security
	* Fix referrer vulnerability when opening an article original link with a shortcut [#2506](https://github.com/FreshRSS/FreshRSS/pull/2506)
	* Slight refactoring of access check [#2471](https://github.com/FreshRSS/FreshRSS/pull/2471)
* UI
	* Optimize dynamic favicon for HiDPI screens [#2539](https://github.com/FreshRSS/FreshRSS/pull/2539)
	* Hide the admin checkbox if user is not admin [#2531](https://github.com/FreshRSS/FreshRSS/pull/2531)
* I18n
	* Add Slovak [#2497](https://github.com/FreshRSS/FreshRSS/pull/2497)
	* Improve Dutch [#2503](https://github.com/FreshRSS/FreshRSS/pull/2503)
	* Improve Occitan [#2519](https://github.com/FreshRSS/FreshRSS/pull/2519), [#2583](https://github.com/FreshRSS/FreshRSS/pull/2583)
* Extensions
	* Additional hooks [#2482](https://github.com/FreshRSS/FreshRSS/pull/2482)
	* New call to change the layout [#2467](https://github.com/FreshRSS/FreshRSS/pull/2467)
* Misc.
	* Make our JavaScript compatible with LibreJS [#2576](https://github.com/FreshRSS/FreshRSS/pull/2576)
	* PDO (database) refactoring for code simplification [#2522](https://github.com/FreshRSS/FreshRSS/pull/2522)
	* Automatic check of CSS syntax in Travis CI [#2477](https://github.com/FreshRSS/FreshRSS/pull/2477)
	* Make our Travis greener by reducing redundant tests [#2589](https://github.com/FreshRSS/FreshRSS/pull/2589)
	* Remove support for sharing with Google+ [#2464](https://github.com/FreshRSS/FreshRSS/pull/2464)
	* Redirect connected users accessing registration page [#2530](https://github.com/FreshRSS/FreshRSS/pull/2530)
	* Add Makefile [#2492](https://github.com/FreshRSS/FreshRSS/pull/2492)

### CODE REVIEW

**Comment by Frenzie** [comment]
Some warning in the log:
```
2019-10-26 15:18:38FreshRSS_CategoryDAO::addColumn: attributes
```

**Comment by Frenzie** [comment]
I don't have an older version at hand atm to double check if this is new or old, but "My labels" doesn't expand when you click the down arrow.

**Comment by Frenzie** [comment]
#2335 defaults to 200, which is *super scary*.

Random example of why:

Screenshot_2019-10-26_15-36-03

But it looks like it should default to off? There might be something slightly odd going on there because that checkmark was checked.

Same for the 3 months thing. Frightening!

**Comment by Alkarex** [comment]
@Frenzie `FreshRSS_CategoryDAO::addColumn: attributes` in the logs is normal and a sign that the database upgrade to the new format has worked. To expand "My labels", it requires that you have added some labels to some articles. ~~The default limit of 200 articles per feed is only for new installations; it is supposed to use the old configuration if it exists;~~ please open a new issue if that does not work. So, it all sounds good :-)

**Comment by Alkarex** [comment]
@Frenzie Sorry, I replied too fast about the default 200-article limit, which is new. Let's discuss what to do with it in another issue. Leave it like that, increase, disable for existing installations, etc.
P.S. Fixed in https://github.com/FreshRSS/FreshRSS/pull/2599

**Comment by Frenzie** [comment]
> To expand "My labels", it requires that you have added some labels to some articles.

Right, and it doesn't work.

Click on down arrow (doesn't work):
Screenshot_2019-10-26_17-27-57

Click on "My labels" (works):
Screenshot_2019-10-26_17-28-13

**Comment by Alkarex** [comment]
@Frenzie Please open a new issue.
P.S. Works for me

**Review by Frenzie — DISMISSED** [review]
Nothing jumps out anymore, all seems well.

**Comment by gpion** [comment]
Hello, will (and if yes when) this release will be available for update via GUI?
 Blast! No update to apply

**Comment by marienfressinaud** [comment]
It will be available tomorrow (or today if I have time but I can't promise)

**Comment by ParoTheParrot** [comment]
Still no update available :-(

**Comment by marienfressinaud** [comment]
Yep sorry, I didn't did the change because we are waiting for a version 1.15.1 https://github.com/FreshRSS/FreshRSS/milestone/40

Edit: I'll do the review for the opened PR but I have some more urgent tasks for now

**Pull request merged**
