### PR TITLE
Fix for #1407

### PR DESCRIPTION
**Pull request by pattems**
Adds new article notifications to reader view. Favicons and titles are not updated in a reader view tab; the code that does this seems to rely on the sidebar, which isn't present in this mode.

### CODE REVIEW

**Comment by pattems** [comment]
Woops, thought of a couple more should-have-been-obvious test conditions that this doesn't pass. Closing until I've got a working solution.

**Comment by Frenzie** [comment]
By the way, I like to use `git pull -r` myself to rebase my commits on top of new upstream.

```bash
# This way you can `git pull upstream dev` (or `master`)
git remote add upstream https://github.com/FreshRSS/FreshRSS.git
# But I prefer to rebase my commits on top
git pull -r upstream dev
```

**Comment by pattems** [comment]
Thanks for the tip!

**Comment by Frenzie** [comment]
While talking tips, also see http://koreader.rocks/doc/topics/Collaborating.html

I also like git-cola for local commit-browsing (although I mostly stick to CLI):
screenshot_2018-12-07_21-01-54

Thanks to GitHub I don't see too much of this branching stuff though ;-)

screenshot_2018-12-07_21-03-22

**Pull request closed without merging**
