### PR TITLE
Trim spaces from user given url

### PR DESCRIPTION
**Pull request by keltroth**
If a user gives an url with spaces an error is thrown... I suggest to avoid those by triming the given url.

### CODE REVIEW

**Comment by Frenzie** [comment]
Note that while trim does strip tabs (which you might accidentally get from tables) it doesn't strip non-breaking spaces (which you might also get from websites). I'm not sure if that matters. :-)

**Review by Frenzie — APPROVED** [review]
Looks good to me.

**Comment by keltroth** [comment]
good point about non breaking spaces... anyway it's still better to trim "normal" spaces :)

**Comment by keltroth** [comment]
Oops, those commits where not intended to come here... Sorry...

**Comment by Frenzie** [comment]
Oh, that needn't be a problem. You can either do something like:

```bash
git reset --hard HEAD~4
```

(because there are four commits you want to get rid of; test on a copied branch first)

Or somewhat safer:

```bash
git rebase -i HEAD~4
```

Then `git push -f`.

**Comment by keltroth** [comment]
Ok thanks for the tip !

**Pull request closed without merging**
