### PR TITLE
More uniform styling of A and BUTTON in drop-downs

### PR DESCRIPTION
**Pull request by Alkarex**
https://github.com/FreshRSS/FreshRSS/issues/1556
https://github.com/FreshRSS/FreshRSS/issues/1548#issuecomment-304445616

### CODE REVIEW

**Comment by Alkarex** [comment]
@Frenzie Please give it a try if you can

**Comment by Frenzie** [comment]
Not tonight; probably not till Tuesday.

**Comment by Frenzie** [comment]
The font-size seems okay, but the alignment is off a fair bit in Fx. To get it to render the same as in other browsers it'd need something like this:

```css
button::-moz-focus-inner {
    padding: 0;
    border: 0
}
```

I imagine this is part of the reason why so many fake link buttons exist.

**Comment by Alkarex** [comment]
@Frenzie I cannot immediately see the problem on my side. Could you please send a screenshot?

**Comment by Frenzie** [comment]
screenshot_2017-05-28_11-42-37

I can't quite get at the bottom of it because the Fx web inspector seems to be broken for me and it's not showing me CSS rules properly (no, I'm not filtering anything).

Also see https://stackoverflow.com/questions/5517744/remove-extra-button-spacing-padding-in-firefox

**Comment by Alkarex** [comment]
With Firefox 53 on Windows 10:
image

With Firefox 52 on Ubuntu 17.04:
image

With Firefox 53 on Ubuntu 17.04:
image

**Comment by Alkarex** [comment]
I was able to see the problem with Firefox 52 on Ubuntu, but with the current version (53) of Firefox, I cannot reproduce the problem on Windows or Ubuntu.
Related Firefox issues:
* https://bugzilla.mozilla.org/show_bug.cgi?id=140562
* https://bugzilla.mozilla.org/show_bug.cgi?id=435697
Seems to be fixed from Firefox 53.

**Comment by Frenzie** [comment]
The current Firefox ESR is 45 but since it's a minor visual glitch let's just ignore it then.

Edit: incidentally, on my Debian Stretch Fx is still at 52. I mistakenly thought it was the latest.

**Pull request merged**
