### PR TITLE
Change confusing naming for label

### LINKED ISSUE #3444: Rename the "tag management" settings page to "label management"
Maybe I am just confused, but doesn't the tag management settings page actually manage labels? My current understanding of tags vs labels is the following:
- Tags can be included in the RSS-Feed inside of `<category></category>`
- Labels are user defined and can be applied to single news items (and there are plans to label them automatically)

If this is correct, we should rename tag management to label management!

### PR DESCRIPTION
**Pull request by aledeg**
Closes #3444

Changes proposed in this pull request:

- Change confusing naming for label

How to test the feature manually:

1. Check label management page

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested
- [ ] unit tests written (optional if too hard)
- [ ] documentation updated

[Additional information can be found in the documentation](https://github.com/FreshRSS/FreshRSS/tree/master/docs/en/developers/04_Pull_requests.md).

Before, labels were referred to as tag which was confusing since
tags are content generated (retrieved from the feed) and label
are user generated.
Now, labels are properly named in their management page.

### CODE REVIEW

**Comment by aledeg** [comment]
@rom-1 Could you check the German translation for this? I've changed a few things and I need your help.
Thank you.

**Comment by rom-1** [comment]
@aledeg I am very sorry, I have no idea how to directly commit to the foreign pull request #3446 without having write permissions. I have almost no experience with github. I figured out how to create pull requests within my fork, but not how to add to existing foreign pull requests which are not part of my fork. This seem to be my limit. ;)

I had to add it to a new PR, I hope this helps. See https://github.com/FreshRSS/FreshRSS/pull/3448

**Comment by aledeg** [comment]
Thank you. I will take care of that!

**Comment by rom-1** [comment]
@aledeg looks good to me 👍

**Comment by aledeg** [comment]
@rom-1 Thank you for reviewing!

**Pull request merged**
