### PR TITLE
Added Raindrop.io as sharing option

### LINKED ISSUE #3716: [Feature] Enable Raindrop.io as a sharing option
FreshRSS is a wonderful aggregator and I would like to be able to share links to my bookmark manager of choice, Raindrop.io

I have added this code locally and will submit under this issue number.

### PR DESCRIPTION
**Pull request by Raineer**
Closes #3716

Changes proposed in this pull request:

Enables Raindrop.io as a supported sharing option, via the Raindrop.io supported URL

How to test the feature manually:

1. From Configuration / Sharing, click + to add a new option
2. Select Raindrop.io from the list. No secondary options are required as the sharing URL is fully prefilled.
3. Browse to an article and select Share. 
4. Note: User must be logged in to Raindrop.io service to complete import of article, but this is the same for most any sharing service.

Pull request checklist:

- [Y] clear commit messages
- [Y] code manually tested
- [N] unit tests written (optional if too hard)
- [N] documentation updated

[Additional information can be found in the documentation](https://github.com/FreshRSS/FreshRSS/tree/edge/docs/en/developers/04_Pull_requests.md).

### CODE REVIEW

**Review by aledeg — CHANGES_REQUESTED** [review]
Please add the translation in the ignore file. You can do that with the cli tool or manually.

**Comment by Raineer** [comment]
The API to support Raindrop.io bookmark addition is documented at: https://help.raindrop.io/third-party-apps

**Comment by Raineer** [comment]
> Please add the translation in the ignore file. You can do that with the cli tool or manually.

Sorry for the overlook, requested changes pushed.

**Review by aledeg — CHANGES_REQUESTED** [review]
For some reason, you still have ` // TODO - Translation` in the conf.php and gen.php files. Please remove them since you've put the translation string in the ignore files.

**Pull request merged**
