### PR TITLE
Tweaks for Vienna RSS

### PR DESCRIPTION
**Pull request by Alkarex**
https://github.com/FreshRSS/FreshRSS/issues/2091
https://github.com/ViennaRSS/vienna-rss/issues/1197

### CODE REVIEW

**Review by Frenzie — COMMENTED** [review]
These encoding changes wouldn't cause any trouble elsewhere?

**Comment by Frenzie** [comment]
Pardon, I just saw the comment stating that it's technically a bug. GH had cleverly hidden the full commit message from my view.

**Comment by Alkarex** [comment]
@Frenzie Those changes should not break existing clients. But additional tests very much welcome. We need to try:
* with `< & > " '` in all text fields such as category name, label name, feed name, feed URL, entry title, entry URL, entry author
* all actions such as retrieve, change read/favourite status, label / unlabel, add, rename, delete
* from the various clients we have access to

Note: the version in FreshRSS's database is always the HTML-escaped version.

**Comment by Alkarex** [comment]
It is a mess for News+, which decodes some HTML entities, but not all of them...

https://github.com/noinnion/newsplus/blob/b06d52a101f3913f5b395b1f512f3cc9c1b86c99/extensions/GoogleReaderCloneExtension/src/com/noinnion/android/newsplus/extension/google_reader/GoogleReaderClient.java#L138-L142

But is it not worse than the situation before my changes.

**Pull request merged**
