### PR TITLE
Fix tag in user query

### LINKED ISSUE #3163: Undefine variable
Hello,
I found a problem

 | Line |  Models/UserQuery.php|      
 | ------ | -------------------------- 
  |157  |  Undefined variable: $tag  |

### PR DESCRIPTION
**Pull request by Alkarex**
#fix https://github.com/FreshRSS/FreshRSS/issues/3163

### CODE REVIEW

**Comment by Alkarex** [comment]
@aledeg I cannot remember how to test a `get` parameter in a user query, can you?

**Comment by Alkarex** [comment]
Merging fast to fix build. This part for sure was wrong, and let's make another PR if there is anything left to be fixed

**Comment by aledeg** [comment]
@Alkarex what do you mean by testing a get parameter?

**Comment by Alkarex** [comment]
@aledeg this `parseTag` function is only used by `parseGet`
https://github.com/FreshRSS/FreshRSS/blob/6fac0e40c4d3bc0e51a124015dcde9b7d766f7b5/app/Models/UserQuery.php#L77-L98
which is in turn only used when there is a `get` parameter:
https://github.com/FreshRSS/FreshRSS/blob/6fac0e40c4d3bc0e51a124015dcde9b7d766f7b5/app/Models/UserQuery.php#L33-L35

**Comment by aledeg** [comment]
Thank you for the explanations, but I still can not understand what you are trying to achieve. I am a bit slow today!

**Comment by Alkarex** [comment]
@aledeg :-) It is just that I do not know the use-case, which requires this `?get=XXX` in UserQuery, and I would like to either test it (to check that is still works as intended) or remove it (if it is obsolete)
https://github.com/FreshRSS/FreshRSS/blob/6fac0e40c4d3bc0e51a124015dcde9b7d766f7b5/app/Models/UserQuery.php#L33-L34

**Comment by aledeg** [comment]
ok, I understand. I'll look into it and I'll let you know.

**Pull request merged**
