### PR TITLE
Increase minimal support to PHP 5.3.8+

### PR DESCRIPTION
**Pull request by Alkarex**
https://github.com/FreshRSS/FreshRSS/issues/1604

### CODE REVIEW

**Comment by Alkarex** [comment]
PHP 5.3.6+ is needed to fix the sanitize bug of https://github.com/FreshRSS/FreshRSS/issues/1604
https://github.com/simplepie/simplepie/blob/45c50e895f0657480c57069b25722dfebec1c8e0/library/SimplePie/Sanitize.php#L368-L375

Patch to increase the minimal PHP version from PHP 5.3.3 to 5.3.8+, based on the fact that 5.3.6 and 5.3.7 do not seem to be used much, and we need 5.3.7+ for some crypto functions.
https://w3techs.com/technologies/details/pl-php/5.3/all (loosing <4.8% of PHP installed base)

* Minimal Debian version increases from 6 (squeeze) to 7 (wheezy, 2013/05) https://distrowatch.com/table.php?distribution=debian
* Minimal CentOS version increases from 6 to 7 (2014/07) https://distrowatch.com/table.php?distribution=centos

**Comment by Alkarex** [comment]
Reference to FreshRSS PHP needs: https://github.com/FreshRSS/FreshRSS/issues/789#issuecomment-73878076

**Comment by Alkarex** [comment]
@marienfressinaud Do you still use CentOS? If yes, which version?

**Comment by marienfressinaud** [comment]
I'm using CentOS 7 but I plan to move quite soon to another distribution

**Pull request merged**
