### PR TITLE
Fix cronjob in Ubuntu Docker image, run as www-data.

### LINKED ISSUE #2339: Ubuntu Docker image cronjob not working
Version 1.14.0, SQLite.

In the release notes of 1.14.0 I found your note that the Ubuntu image is much faster then the Alpine one. So I switched, naturally. After the switch to 1.14.0 and Ubuntu I experienced a dramatic reduction in news entries. I figured out that this is due to the fact that cron is not running, only my feeds that support WebSub still appear.

After digging a bit deeper I think it's related to `/var/spool/cron/crontabs/root`, which looks like this: `*/20 su apache -s /bin/sh -c 'php /var/www/FreshRSS/app/actualize_script.php' 2>> /proc/1/fd/2 > /tmp/FreshRSS.log`. The user `apache` is not available on Ubuntu, it should read **www-data**. Fixing it by hand only works until I recreate the container (or `docker-compose up -d`).

### PR DESCRIPTION
**Pull request by neur0manc**
This should fix #2339

### CODE REVIEW

**Comment by Alkarex** [comment]
Thanks, but it is supposed to be [already fixed](https://github.com/FreshRSS/FreshRSS/issues/2319) in our /dev branch, and [release candidate 1.14.1](https://github.com/FreshRSS/FreshRSS/pull/2338) is open for testing.
Could you please give a try to the `:dev` Docker image?

Future pull requests much welcome, but please remember to target our /dev branch.

**Comment by Alkarex** [comment]
This is a precise duplicate of https://github.com/FreshRSS/FreshRSS/pull/2321
Additional fixes : https://github.com/FreshRSS/FreshRSS/pull/2325 + https://github.com/FreshRSS/FreshRSS/pull/2326

**Comment by neur0manc** [comment]
> Could you please give a try to the `:dev` Docker image?

I did, it works.

> Future pull requests much welcome, but please remember to target our /dev branch.

I will. Sorry I caused unnecessary work. Have a nice day!

**Comment by Alkarex** [comment]
Thanks for the feedback!

**Pull request closed without merging**
