### PR TITLE
Remove Google+ support

### PR DESCRIPTION
**Pull request by ghost**
Google+ has been dead for a while now.

### CODE REVIEW

**Comment by Frenzie** [comment]
This looks like only the translation strings and not the code? Or do you mean this is a leftover from a previous cleanup?

**Comment by aledeg** [comment]
It's only the translation strings. There are other places were it's in use. In ```app/shares.php``` for instance.

**Comment by ghost** [comment]
> It's only the translation strings. There are other places were it's in use. In `app/shares.php` for instance.

I have included app/shares.php, but I didn't find anything other than that and translation strings.

https://github.com/FreshRSS/FreshRSS/pull/2464/files#diff-29a558e3108b5864daf75d27247eba30

**Review by Frenzie — APPROVED** [review]
lgtm

**Comment by aledeg** [comment]
I think you need to rebase your branch since there is an extra commit in your PR!

**Comment by ghost** [comment]
Sorry, I don't know how it crawled in. I have removed that.

**Pull request merged**
