### PR TITLE
Switch to FreshRss tab

### PR DESCRIPTION
**Pull request by Crupuk**
Switch to FreshRss tab when notification is clicked and close notification

### CODE REVIEW

**Comment by Alkarex** [comment]
Thanks for the contribution, @Crupuk :-)
Could you please check the white-space to use the same style as the lines above? (tabs)

**Comment by Crupuk** [comment]
Done ;-)

**Comment by Alkarex** [comment]
Thanks 👍  Last thing: could you please re-send the pull request for the /dev branch, and not the /master branch?

**Comment by Crupuk** [comment]
I think it's good now.

**Pull request merged**
