### PR TITLE
Fix hide articles + batch option

### PR DESCRIPTION
**Pull request by Alkarex**
https://github.com/FreshRSS/FreshRSS/issues/2332
https://github.com/FreshRSS/FreshRSS/issues/2345
Re-introduces the instant-remove article.
Batch mark-as-read only used for fast actions like scroll and keyboard
shortcut for next/previous articles.

### CODE REVIEW

**Comment by Alkarex** [comment]
Arg, now the articles disappear during expansion. Fix coming

**Comment by aledeg** [comment]
You'll get there eventually!

**Comment by Alkarex** [comment]
Fixed in https://github.com/FreshRSS/FreshRSS/pull/2352

**Comment by squromiv** [comment]
Installed #2352. Option "Hide articles after reading" works normally, as earlier.

**Comment by Alkarex** [comment]
Thanks for the test! A few more patches have just landed in the /dev branch before the imminent release of [FreshRSS 1.14.1](https://github.com/FreshRSS/FreshRSS/pull/2338). Additional tests welcome on the /dev branch.

**Comment by squromiv** [comment]
@Alkarex I have checked again and must note, that currently viewing article is not hidden, when it is marked as read. I think, it should be corrected.

**Comment by Alkarex** [comment]
Hum, then there would be an option conflict with marking-as-read automatically, which would make it impossible to read an article. This is actually what I fixed in https://github.com/FreshRSS/FreshRSS/pull/2352
How do you mark an article as read in your case?

**Comment by squromiv** [comment]
v.1.13.1

v.1.14.1-dev
1 14 1-dev

**Comment by Alkarex** [comment]
Ok @squromiv , could you please test https://github.com/FreshRSS/FreshRSS/pull/2354 ?

**Comment by Alkarex** [comment]
Merged in /dev . Additional tests welcome

**Comment by squromiv** [comment]
Good job!
And what do you think about such an option? I would prefer to use something like this.
screen_2019 04 07 00111
Is there anybody, who interested in it?

**Pull request merged**
