### PR TITLE
Use HTTP_X_FORWARDED_

### PR DESCRIPTION
**Pull request by Alkarex**
https://github.com/FreshRSS/FreshRSS/issues/975

### CODE REVIEW

**Comment by Alkarex** [comment]
Not yet tested.

**Comment by Alkarex** [comment]
The test to be done is to check if `base_url` is generated correctly during install, without proxy. Then possibly with a proxy.

**Comment by marienfressinaud** [comment]
Seems good to me be I would like to validate it's working first. However, I don't have the corresponding configuration to test it :(

**Comment by marienfressinaud** [comment]
Merged into https://github.com/FreshRSS/FreshRSS/commit/529a28567f7166b7e4ed1ff62388b86765f71226 (I made a little fix before merging, that's the reason why GitHub think this PR is not merged)

**Pull request closed without merging**
