### PR TITLE
Update link to News+ Google Reader extension

### PR DESCRIPTION
**Pull request by Alwaysin**
Remove News+ (Google Reader extension does not exist anymore)

### CODE REVIEW

**Comment by Alkarex** [comment]
Still exists for me 😮 https://play.google.com/store/apps/details?id=com.noinnion.android.newsplus
(or at worst https://github.com/noinnion/newsplus/tree/master/extensions/GoogleReaderCloneExtension/src/com/noinnion/android/newsplus/extension/google_reader )
And I use it every day...

**Comment by Alwaysin** [comment]
I swear I couldn't find it when searching in the store! I'm glad it is still there, gonna use it again.

But could you then update the link which seems to have changed?

**Comment by Alkarex** [comment]
Ah sorry, I read too fast. The link to the extension is indeed dead

**Comment by Alwaysin** [comment]
Hmmm... The application in itself still exists, but the extension doesn't anymore, does it?

EDIT: crossed messages!

**Comment by Alkarex** [comment]
Could you please update the extension link to https://github.com/noinnion/newsplus/blob/master/apk/GoogleReaderCloneExtension_101.apk ?

**Comment by Alwaysin** [comment]
Okay, should be good!

**Pull request merged**
