### PR TITLE
i18n: German update

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Alkarex** [comment]
Thanks @thomasE1993  :-)
I have merged your changes in the /dev branch manually (cherry-pick) https://github.com/FreshRSS/FreshRSS/commit/044c4428062ea215c9fe2f46fb47078854048e61
Next time, please remember to target /dev ;-)
Although I do not speak German, I believe there was a typo at "Inaktive".

Any comment @ealdraed?

**Comment by Alkarex** [comment]
Cf. https://github.com/FreshRSS/FreshRSS/pull/766

**Comment by Alkarex** [comment]
@thomasE1993 Your contribution will be included in the next version beta 1.1.1, due this month.

**Comment by ealdraed** [comment]
@Alkarex Yes, that was a typo. Thanks for spotting it ;)

I will have a look at the changes when I have some time.

**Pull request closed without merging**
