### PR TITLE
Minz Dispatcher Controllers path

### PR DESCRIPTION
**Pull request by Alkarex**
https://github.com/FreshRSS/FreshRSS/pull/1704

### CODE REVIEW

**Comment by Alkarex** [comment]
* The constant was apparently never used
* I have not found any path using this code (maybe some extensions, but I have checked the listed ones, and they do not use it)

https://github.com/FreshRSS/FreshRSS/blob/4e174ed9dd84ce4f8de410baf6a6e0fde9160055/lib/Minz/Dispatcher.php#L152

* FreshRSS uses an uppercase `./Controllers/` directory
* Other places in the code are uppercased 

https://github.com/FreshRSS/FreshRSS/blob/d91a92434f516a9e25bf0dca608a0221094d0489/lib/Minz/Error.php#L24

**Comment by Alkarex** [comment]
@kevinpapst Did you have an example using the lowercase `./controllers/` ?

**Comment by kevinpapst** [comment]
I was trying to write a full fledged extension and the controllers didn't load, exactly due to the code part that you changed now. It did not work until I used lowercase "controllers" like here: https://github.com/kevinpapst/freshrss-wall/tree/master/xExtension-Wall

The code that you changed is very likely ONLY used by extensions. I have not seen an extension using controllers by now, but surely there are (probably in Mariens private playground only) otherwise the code wouldn't be there and work ;-)

Its only executed if you manually register a controller like that:
https://github.com/kevinpapst/freshrss-wall/blob/master/xExtension-Wall/extension.php#L18

You probably will only break my demo extension, which is no big deal, but you better write it in bold letters into the release notes that there is a backward compatibility break coming in.

Edit: Its a BC break and I personally like lowercase more, but I would still vote for uppercase for consistency within FreshRSS

**Comment by Alkarex** [comment]
Thanks for the feedback. Yes, maybe @marienfressinaud , otherwise I believe you are likely the first to use this feature :-)

**Review by marienfressinaud — APPROVED** [review]
It seems ok to me but I don't understand why it was working until now

**Comment by Alkarex** [comment]
It was working because FreshRSS and extensions are using two different if/else paths:
https://github.com/FreshRSS/FreshRSS/blob/4e174ed9dd84ce4f8de410baf6a6e0fde9160055/lib/Minz/Dispatcher.php#L77-L82
and the lowercase was in `self::loadController(...);`

**Pull request merged**
