### PR TITLE
Duplicates items no guid

### PR DESCRIPTION
**Pull request by Alkarex**
https://github.com/FreshRSS/FreshRSS/issues/1552

### CODE REVIEW

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/1548#issuecomment-304384060

**Comment by Alkarex** [comment]
Merging fast to get tests on /dev

**Comment by Frenzie** [comment]
Works as it should on my test feeds. The `link` is taken as the GUID again, preventing duplicates.

**Comment by Alkarex** [comment]
Thanks for the feedback, @Frenzie :-)

**Pull request merged**
