### PR TITLE
API Reeder compatibility

### LINKED ISSUE #2513: Frequent authentication errors when trying to access Google Reader API via Reeder
After initially logging in fine, I keep getting authentication errors later when trying to mark articles as read or sync my feeds via Reeder. Initial sync seems to work well, but later it doesn't. Are there known issues using Reeder with FreshRSS via Google Reader API or is there an additional setting I need to change in FreshRSS to make it work?

### PR DESCRIPTION
**Pull request by Alkarex**
Fixes #2513

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
Bit weird (from Feeder) but looks okay.

**Comment by marienfressinaud** [comment]
So one can authenticate by sending an empty token (or "x")? :scream:

**Comment by Frenzie** [comment]
You still need to have authenticated with user+pass, right?

**Comment by Alkarex** [comment]
As @Frenzie writes, one still needs the full credentials if one does not provide a token

**Comment by marienfressinaud** [comment]
Oh, ok then! :)

**Pull request merged**
