### PR TITLE
Update git command

### PR DESCRIPTION
**Pull request by aledeg**
I removed an unnecessary option and rewrote a short option
to use the long option. I find it's easier to understand
long options when you don't type them.

### CODE REVIEW

**Comment by Alkarex** [comment]
Ups, I merged too fast without reading carefully enough: one of the `-f` has disappeared. It was meant to be with a double `-f`
https://git-scm.com/docs/git-clean
Could you please fix @aledeg ?

**Comment by aledeg** [comment]
@Alkarex Oups, I didn't read git documentation thoroughly. My bad

**Comment by Frenzie** [comment]
As an aside, in principle I agree but -f is pretty straightforward. :-)

**Comment by aledeg** [comment]
I've reverted it anyway :)

**Pull request merged**
