### PR TITLE
Install routine freshup

### PR DESCRIPTION
**Pull request by math-GH**
Install routine freshup

Changes proposed in this pull request:
- full FreshRSS icon in the header
- navigation: next steps only available via button (next steps via navigation are disabled)
- real headline

now it looks like:
grafik

How to test the feature manually:

1. run the install routine

Pull request checklist:

- [ ] clear commit messages
- [x] code manually tested
- [ ] unit tests written (optional if too hard)
- [ ] documentation updated

### CODE REVIEW

**Comment by Alkarex** [comment]
Thanks, that looks good, but please check the conflict. Make sure you have the latest changes from the edge branch, including your own https://github.com/FreshRSS/FreshRSS/pull/3713

**Comment by math-GH** [comment]
> 
> 
> Thanks, that looks good, but please check the conflict. Make sure you have the latest changes from the edge branch, including your own #3713

Done.
(Strange. This conflict was not shown in Github Desktop app.)

**Comment by Alkarex** [comment]
Why is the new SVG file needed? Couldn't the existing `icon.svg` or `favicon.svg` be reused?

**Comment by math-GH** [comment]
> 
> 
> Why is the new SVG file needed? Couldn't the existing `icon.svg` or `favicon.svg` be reused?

Both icons have just the circle without the text "FreshRSS".
I use now the official "full logo" that is from https://github.com/FreshRSS/FreshRSS/tree/edge/docs/img

Now the logo is a "real" logo without adding a text node right after the circle icon. 
Now it is assured that the correct font family is used for the logo (because it is inside of the svg file).
Now this CSS is not anymore needed, that avoid the underline while hovering the logo.
grafik

**Pull request merged**
