### PR TITLE
Fix doc links

### PR DESCRIPTION
**Pull request by Alkarex**
Many broken links.
Related to https://github.com/FreshRSS/FreshRSS/pull/2614

### CODE REVIEW

**Comment by Alkarex** [comment]
Any idea why https://freshrss.github.io/FreshRSS/en/contributing.html is not working?

**Comment by aledeg** [comment]
On [that page](https://freshrss.github.io/FreshRSS/en/), the anchor is on a MD extension. It looks like it was not converted to html.

**Comment by Frenzie** [comment]
Is there anything particular blocking #2590 that you'd like me to address?

**Comment by Alkarex** [comment]
Sorry @Frenzie, I forgot about that one 🙄

**Comment by Frenzie** [comment]
No problem, it's just that I'd prefer not to keep adapting to new changes given that I see it as fundamentally mergeable. :-) There are a few French translations still missing, but nothing that wasn't missing before the PR. On the contrary, thanks to the PR it's incredibly easy to translate the remainder.

**Pull request merged**
