### PR TITLE
Improved German translation of "related tags"

### PR DESCRIPTION
**Pull request by math-GH**
grafik

Changes proposed in this pull request:

- better translation in German for the article tags. "Verwandte Tags" is not a good translation. The word "Tag"/"Tags" is quite difficult because it looks like "Tag"(=Day). I would suggest to use the word "Hashtag" that makes it more clear

How to test the feature manually:

1. see at the end of article.

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested

### CODE REVIEW

**Comment by Frenzie** [comment]
What about something like label/zettel/etikett? Hashtag seems weird to me, unless that's how you use it in German these days.

**Comment by math-GH** [comment]
> What about something like label/zettel/etikett? Hashtag seems weird to me, unless that's how you use it in German these days.

`label` is already used by the label feature (see left of the "hashtag").
`Zettel` and `Etikett` are not used. It is the correct translation in the non-online-world, but not used for digital. In digital world we use the English words "Tag" and "Hashtag" similar.

**Comment by Frenzie** [comment]
Right, but a tag isn't a hashtag.

**Comment by Frenzie** [comment]
But if you think it works well enough in German. :)

**Review by Frenzie — APPROVED** [review]

**Pull request merged**
