### PR TITLE
Added informations for systemd service

### PR DESCRIPTION
**Pull request by Offerel**

### CODE REVIEW

**Comment by Alkarex** [comment]
@Offerel Could you please make a new PR for the icon? So that we keep this one for systemd?
By the way, the reason I have not merged yet is because I would like this info to be in our docs https://github.com/FreshRSS/FreshRSS/issues/2557#issuecomment-538683148 as apposed to our readme (it would be fine with a link from the readme, though)

**Comment by Alkarex** [comment]
And please remember to checkout our /dev branch for making changes, not /master

**Comment by Offerel** [comment]
Sorry for the confusion I've made. I did the whole thing about the GUI of GitHub on the web and unfortunately also on the master branch. I have now checked out the dev branch and will implement future changes there. Could it be that the WebGUI always summarizes later commits in the previous PR? Or am I just doing something wrong? At home I mostly use Visual Studio Code and let it do the commits for my own projects, I only use this WebGUI on the road.

**Comment by Alkarex** [comment]
No worries. You first need to make a new branch (for instance, branching from /dev into /systemd-doc) , and then you can make as many edits there as you want, which will be in the same PR.

**Comment by Alkarex** [comment]
Implemented in https://github.com/FreshRSS/FreshRSS/pull/2605

**Pull request closed without merging**
