### PR TITLE
Filter actions

### PR DESCRIPTION
**Pull request by Alkarex**
Feed actions based on search filters. ~~Work in progress~~

### CODE REVIEW

**Comment by aledeg** [comment]
I've started to play around with something similar the other day but as an extension :)
I can't wait to see that in action :+1:

**Comment by Alkarex** [comment]
Ah yes, an extension would work too. I think this might be a feature popular enough to make it to the core. If you have any code or concept that can be used here, do tell :-)

**Comment by aledeg** [comment]
I was thinking about highlighting the matches, or highlighting the sentence of the matches, or highlighting the paragraph of the matches.

**Comment by Alkarex** [comment]
For 1.14.0, I think I will only have the *auto mark as read* feature, but the structure is ready for e.g. auto-favourite, auto-tag, etc.

image

image

**Comment by Alkarex** [comment]
Let's continue testing in /dev

**Comment by Alkarex** [comment]
Contributes to
https://github.com/FreshRSS/FreshRSS/issues/2216
https://github.com/FreshRSS/FreshRSS/issues/1368

**Comment by Jucgshu** [comment]
Hi @Alkarex 

Being too excited about this features is probably the reason I can't find it in the 1.14.0 version?

I can create filters just fine, but can't seem to find how to setup the filter actions. Is there something I miss?

I use the FreshRSS's Docker version and upgraded from the official image this PM.

Thanks.

-j

**Comment by aledeg** [comment]
@Jucgshu you can find it on every feed configuration!

**Comment by Jucgshu** [comment]
Oww ok, I was kinda hoping to find a global option, but that's probably for later then.

That's already a big step forward and a very cool feature to have.

Thanks team (and thanks @aledeg for the swift answer ;p)

-j

**Comment by Alkarex** [comment]
@Jucgshu Is it mainly a global filter for automatically marking as read, which you want?

**Comment by Jucgshu** [comment]
Having filter actions per feeds is *very* cool, but I have to say: having the ability to extend the existing filter feature would allow to do what I'd love to do with FreshRSS: achieve the no-spoiler feature by marking as read articles based on search, regardless of the setup of the feeds.

That would be a killer, yes, having this option in the 'filter' option panel and be able to define actions per filters.

**Comment by SecT0uch** [comment]
Thanks @Alkarex for your work.
How does it work for a multi-word filter ? 
I added these filters last day :
```
intitle:'Revue de presse de l'April pour la semaine'
intitle:'Agenda du Libre pour la semaine'
```
But it doesn't seem to work.
Is a newline interpreted as a *OR* ?
Maybe the right way to do is to put both filters on the same line, with a *OR* between them ?

**Comment by Alkarex** [comment]
Yes, with `OR` on the same line
Check the documentation https://freshrss.github.io/FreshRSS/en/users/03_Main_view.html#with-the-search-field

**Pull request merged**
