### PR TITLE
Improve translation tools

### PR DESCRIPTION
**Pull request by aledeg**
I was not happy with the previous version. I refactored everything to make it reusable.
It allows me do do more verifications and to build a tool to handle the files themselves.

### CODE REVIEW

**Comment by Frenzie** [comment]
Looks good to me, but if you want me to take an in-depth look you'll have to wait till tomorrow. :-)

**Review by Frenzie — APPROVED** [review]
Excellent work!

**Comment by aledeg** [comment]
Thanks!

**Comment by Alkarex** [comment]
Could you please add a little line in the changelog about that?

**Comment by aledeg** [comment]
@Alkarex Done!

**Pull request merged**
