### PR TITLE
Docs: Add Fluent Reader to API Clients

### PR DESCRIPTION
**Pull request by NoNamePro0**
Fluent Reader is a desktop RSS reader built with Electron, React, and Fluent UI supporting Fever API.

See more: https://github.com/yang991178/fluent-reader

Changes proposed in this pull request:

- Add Fluent reader to API clients

Pull request checklist:

- [x] clear commit messages
- [x] documentation updated

[Additional information can be found in the documentation](https://github.com/FreshRSS/FreshRSS/tree/master/docs/en/developers/04_Pull_requests.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
I would add a new section for software which support mac, windows and linux instead of adding the link 3 times.

**Comment by aledeg** [comment]
Or make it as a table. See the README file for an example.

**Comment by aledeg** [comment]
@NoNamePro0 Nice! Could you change the header **Free Software** for **Licence**.
Anyway, thank you for your contribution! Remember to add your name in the contributor file in the current PR.

**Comment by NoNamePro0** [comment]
Done! 😊

**Review by aledeg — APPROVED** [review]

**Comment by Alkarex** [comment]
Thanks @NoNamePro0  👍 
Would you be able to put the same table in the French doc as well?
https://github.com/FreshRSS/FreshRSS/blob/master/docs/fr/users/06_Fever_API.md

We also need to update the client overview in our main readme, but I will try to do that myself
* https://github.com/FreshRSS/FreshRSS/blob/master/README.md#apis--native-apps
* https://github.com/FreshRSS/FreshRSS/blob/master/README.fr.md#apis-et-applications-natives

But please do tell which feature you already know are available or not.

**Comment by NoNamePro0** [comment]
> We also need to update the client overview in our main readme, but I will try to do that myself
> 
>* https://github.com/FreshRSS/FreshRSS/blob/master/README.md#apis--native-apps
>* https://github.com/FreshRSS/FreshRSS/blob/master/README.fr.md#apis-et-applications-natives
> 
> But please do tell which feature you already know are available or not.

| App                                             | Platform              | Free Software                                    | Maintained & Developed | API   | Works offline | Fast sync | Fetch more in individual views | Fetch read articles | Favourites | Labels | Podcasts | Manage feeds |
|:------------------------------------------------|:---------------------:|:------------------------------------------------:|:----------------------:|:-----:|:-------------:|:---------:|:------------------------------:|:-------------------:|:----------:|:------:|:--------:|:------------:|
| [Fluent Reader](https://hyliu.me/fluent-reader/)| Windows, Linux, MacOS| [✔️](https://github.com/yang991178/fluent-reader)| ✔️✔️                   | Fever | ✔️             | ⭐⭐⭐       | ❔                    | ❔                 | ✔️         | ➖     | ➖       | ❔           |

**Pull request merged**
