### PR TITLE
Scroll as read

### PR DESCRIPTION
**Pull request by Alkarex**
https://github.com/FreshRSS/FreshRSS/issues/1258
https://github.com/FreshRSS/FreshRSS/issues/707
Should works for all views. Simplified logic.

### CODE REVIEW

**Comment by Alkarex** [comment]
Addresses some of the needs of https://github.com/FreshRSS/FreshRSS/issues/329

**Comment by chemical1979** [comment]
In the german translation, "... while scrolling" is translated into ".. beim blättern", which is a term that is mainly is used for "switching or skipping pages" which does not match an endless list of elements. 

Background: I just clicked in an article that was not at the top of my feed in the normal view, and after this, I noticed that all other articles in front of that one "were gone" (I noticed this too late and I have no idea which articles slipped through now). But anyway, this is not what I wanted to say: I jumped into the configuration and try to find a setting that matches this behaviour and I looked for sth like "mark as read ... while skipping". But I did not find it. I went here and searched an eventually found this issue.

@Alkarex Long story short: The translation "... while scrolling" should be "... while scrolling/skipping" in English and "... beim Scrollen/Überspringen" in German. :-)

**Comment by Alkarex** [comment]
@chemical1979 Thanks. Would you be able to make a pull request for this change?

**Comment by chemical1979** [comment]
I'm not a git expert, but as this is the second time you ask me, perhaps it is the challenge I need to become one. :-)

**Comment by Alkarex** [comment]
You did very well :-) For reference https://github.com/FreshRSS/FreshRSS/pull/2026

**Pull request merged**
