### PR TITLE
Change layout for the share options on mobile

### PR DESCRIPTION
**Pull request by aledeg**
Before, it was impossible to click on links to share on small screens.
Now, all dropdowns are opened at the bottom of the screen and stays there.

Linked to #1506

### CODE REVIEW

**Comment by Frenzie** [comment]
Where is this dropdown menu? Whenever I see `!important` my spidey senses start tingling. :-P

**Comment by aledeg** [comment]
@Frenzie I know :)
The dropdown menu are the one that you can see when you click on the share button and on the user queries. I used ```!important``` because I want to make sure that there is no radius on that dropdown since I display it at the bottom of the screen and it uses the whole space. The round corner was quite disgraceful.
Feel free to come with a better solution.

**Comment by Alkarex** [comment]
Would it be possible to find a more qualified rule, hence avoiding the need of `!important` ?

**Comment by Frenzie** [comment]
I don't really want to figure out where this sharing thing is right now[1] but for the user query button you could increase specificity by using something like `.dropdown .dropdown-menu`.

[1] It looks like my settings say sharing in the bottom line but I suppose I'd have to set up some sharing for it to display.

**Comment by aledeg** [comment]
@Frenzie @Alkarex Done. I removed the ```!important```

**Review by Frenzie — APPROVED** [review]

**Pull request merged**
