### PR TITLE
Add more glyphs for opensans font

### PR DESCRIPTION
**Pull request by asmfreak**
This pull request is a continuation of work for #1028, but in a cleaner way. I deleted my fork and reforeked the repository. This pr fixes #1028 .

### CODE REVIEW

**Comment by Alkarex** [comment]
Related to https://github.com/FreshRSS/FreshRSS/pull/1085

**Comment by Alkarex** [comment]
This pull request has been forgotten a bit. Sorry for that. Let's try to complete it.
@ASMfreaK If you are still around, could you please allow edits from maintainers in this pull-request?
image
Or at least fix the conflict?

Furthermore, I would rather like to avoid the additional `opensans.css` file if possible, for instance by putting the rules in template.css (which currently seems acceptable to me since all themes use OpenSans so far).

Here is my patch:

```patch
From 5c11c3ad9a5048444b79ce9095661ba99b05722a Mon Sep 17 00:00:00 2001
From: Alexandre Alapetite <alexandre@alapetite.fr>
Date: Sat, 2 Dec 2017 11:23:03 +0100
Subject: [PATCH 8/8] Avoid additional CSS file

---
 p/.htaccess                          |  2 +-
 p/themes/BlueLagoon/BlueLagoon.css   |  3 ---
 p/themes/Dark/dark.css               |  3 ---
 p/themes/Flat/flat.css               |  3 ---
 p/themes/Origine/origine.css         |  3 ---
 p/themes/Pafat/pafat.css             |  3 ---
 p/themes/Screwdriver/screwdriver.css |  3 ---
 p/themes/base-theme/base.css         |  3 ---
 p/themes/base-theme/template.css     | 11 +++++++++++
 p/themes/fonts/opensans.css          |  9 ---------
 10 files changed, 12 insertions(+), 31 deletions(-)
 delete mode 100644 p/themes/fonts/opensans.css

diff --git a/p/.htaccess b/p/.htaccess
index 4c74a209..9c40107c 100644
--- a/p/.htaccess
+++ b/p/.htaccess
@@ -42,7 +42,7 @@ AddDefaultCharset	UTF-8
 </IfModule>
 
 <IfModule mod_headers.c>
-	<FilesMatch "\.(css|html|js|ico|gif|png|woff)$">
+	<FilesMatch "\.(css|html|js|ico|gif|png|svg|ttf|woff|woff2)$">
 		Header	merge Cache-Control "public"
 	</FilesMatch>
 </IfModule>
diff --git a/p/themes/BlueLagoon/BlueLagoon.css b/p/themes/BlueLagoon/BlueLagoon.css
index 8072dfb1..99d30c7d 100644
--- a/p/themes/BlueLagoon/BlueLagoon.css
+++ b/p/themes/BlueLagoon/BlueLagoon.css
@@ -1,8 +1,5 @@
 @charset "UTF-8";
 
-/*=== FONTS */
-@import url("../fonts/opensans.css");
-
 /*=== GENERAL */
 /*============*/
 html, body {
diff --git a/p/themes/Dark/dark.css b/p/themes/Dark/dark.css
index 4245fc1a..c2d35b36 100644
--- a/p/themes/Dark/dark.css
+++ b/p/themes/Dark/dark.css
@@ -1,8 +1,5 @@
 @charset "UTF-8";
 
-/*=== FONTS */
-@import url("../fonts/opensans.css");
-
 /*=== GENERAL */
 /*============*/
 html, body {
diff --git a/p/themes/Flat/flat.css b/p/themes/Flat/flat.css
index 92ed9b9a..f2ce77a0 100644
--- a/p/themes/Flat/flat.css
+++ b/p/themes/Flat/flat.css
@@ -1,8 +1,5 @@
 @charset "UTF-8";
 
-/*=== FONTS */
-@import url("../fonts/opensans.css");
-
 /*=== GENERAL */
 /*============*/
 html, body {
diff --git a/p/themes/Origine/origine.css b/p/themes/Origine/origine.css
index 22ec9859..4fe77bc0 100644
--- a/p/themes/Origine/origine.css
+++ b/p/themes/Origine/origine.css
@@ -1,8 +1,5 @@
 @charset "UTF-8";
 
-/*=== FONTS */
-@import url("../fonts/opensans.css");
-
 /*=== GENERAL */
 /*============*/
 html, body {
diff --git a/p/themes/Pafat/pafat.css b/p/themes/Pafat/pafat.css
index b7c4d690..17f4ebe1 100644
--- a/p/themes/Pafat/pafat.css
+++ b/p/themes/Pafat/pafat.css
@@ -1,8 +1,5 @@
 @charset "UTF-8";
 
-/*=== FONTS */
-@import url("../fonts/opensans.css");
-
 /*=== GENERAL */
 /*============*/
 html, body {
diff --git a/p/themes/Screwdriver/screwdriver.css b/p/themes/Screwdriver/screwdriver.css
index 5394d7f5..7a7c2f94 100644
--- a/p/themes/Screwdriver/screwdriver.css
+++ b/p/themes/Screwdriver/screwdriver.css
@@ -1,8 +1,5 @@
 @charset "UTF-8";
 
-/*=== FONTS */
-@import url("../fonts/opensans.css");
-
 /*=== GENERAL */
 /*============*/
 html, body {
diff --git a/p/themes/base-theme/base.css b/p/themes/base-theme/base.css
index 269e4653..993508f5 100644
--- a/p/themes/base-theme/base.css
+++ b/p/themes/base-theme/base.css
@@ -1,8 +1,5 @@
 @charset "UTF-8";
 
-/*=== FONTS */
-@import url("../fonts/opensans.css");
-
 /*=== GENERAL */
 /*============*/
 html, body {
diff --git a/p/themes/base-theme/template.css b/p/themes/base-theme/template.css
index 17a43d3e..3869008b 100644
--- a/p/themes/base-theme/template.css
+++ b/p/themes/base-theme/template.css
@@ -2,9 +2,20 @@
 
 /*=== GENERAL */
 /*============*/
+@font-face {
+	font-family: 'OpenSans';
+	font-style: normal;
+	font-weight: 400;
+	src: local('Open Sans'), local('OpenSans'),
+	url('../fonts/OpenSans.woff2') format('woff2'),
+	url('../fonts/OpenSans.woff') format('woff'),
+	url('../fonts/OpenSans.ttf') format('truetype'),
+}
+
 html, body {
 	margin: 0;
 	padding: 0;
+	font-family: "OpenSans", "Cantarell", "Helvetica", "Arial", sans-serif;
 	font-size: 100%;
 }
 
diff --git a/p/themes/fonts/opensans.css b/p/themes/fonts/opensans.css
deleted file mode 100644
index 3dab7a35..00000000
--- a/p/themes/fonts/opensans.css
+++ /dev/null
@@ -1,9 +0,0 @@
-@font-face {
-	font-family: 'OpenSans';
-	font-style: normal;
-	font-weight: 400;
-	src: local('Open Sans'), local('OpenSans'),
-	url('../fonts/opensans.woff2') format('woff2'), /* Super Modern Browsers */
-	url('../fonts/opensans.woff') format('woff'), /* Modern Browsers */
-	url('../fonts/opensans.ttf') format('truetype'), /* Safari, Android, iOS */
-}
-- 
2.11.0.windows.3
```

**Comment by asmfreak** [comment]
I'm sorry I currently don't have time to edit this by hand. I've allowed edits from maintainers so you can fix this. Sorry for inconvenience.

**Comment by Alkarex** [comment]
That is very fine @ASMfreaK 👍 
Any comment before merging, e.g. @Frenzie ?

**Comment by Frenzie** [comment]
Yes actually, it looks like there's some issue with cases. `OpenSans.woff2` (an example from the CSS) doesn't exist judging by this PR, whereas `opensans.woff2` does. Also we have both a openSans.woff and opensans.woff file.

As an aside, the font family names don't have to be quoted here (there are no spaces or punctuation marks in the names) in case that makes a difference.

**Comment by Alkarex** [comment]
Well spotted @Frenzie ; the case change was lost in a revert along the way :-)

**Pull request merged**
