### PR TITLE
fix: Make sure to have user conf in hasAccess

### PR DESCRIPTION
**Pull request by marienfressinaud**
Closes #

Changes proposed in this pull request:

- Make sure to have user conf in hasAccess

The `FreshRSS_Auth::hasAccess` method is called during auth
initialization (`app/FreshRSS.php:78`), only for `user#create` action.
However, at this step, the `user` configuration namespace hasn't be
initialized yet, and so users weren't able to register because of the
exception... quite critical!

How to test the feature manually:

1. As an admin, make sure registrations are opened
2. Log out
3. Try to register a new user
4. It works! (it didn't before this patch)
5. As a new user, make sure you don't have administrator rights

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested
- [ ] unit tests written (optional if too hard)
- [ ] documentation updated

[Additional information can be found in the documentation](https://github.com/FreshRSS/FreshRSS/tree/master/docs/en/developers/04_Pull_requests.md).

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
lgtm

**Comment by Alkarex** [comment]
This bug was not in the previous release, right? Only in the /master branch

**Comment by marienfressinaud** [comment]
Yes, it was introduced in https://github.com/FreshRSS/FreshRSS/commit/3c099c78537020eae3b6fe060fbe86088e996c83 just a few days ago, no need for a new version :)

**Comment by Alkarex** [comment]
I will try to find time to write the changelog later this week-end, and it was just to know whether that was new or not :-)

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/2709

**Comment by marienfressinaud** [comment]
I was thinking that adding a line in the changelog might be a task to add to the pull request template?

**Comment by Alkarex** [comment]
@marienfressinaud I do not like changelog entries to be part of a PR because it very frequently (like in more often than not) create conflicts.
Edit: But maybe your proposition is a line in the PR comment?

**Comment by marienfressinaud** [comment]
It makes sense :+1: my proposition was to add the line directly to the changelog file, but my experience of that is mainly based on solo-projects. Never mind! :)

**Pull request merged**
