### PR TITLE
Fix bug when using double authentication

### PR DESCRIPTION
**Pull request by Alkarex**
https://github.com/FreshRSS/FreshRSS/issues/1807

### CODE REVIEW

**Comment by Alkarex** [comment]
@plopoyop The fix I did for Yunohost HTTP login https://github.com/FreshRSS/FreshRSS/pull/1756 introduced a bug for people using double authentication (HTTP login + Web form), which should be fixed with this patch. Let me know if you get a chance to give it a try.
By the way, if you have not yet updated the Yunohost package to 1.10.0, you can skip it and go directly for 1.10.1, which I will try to release during the week-end :-)

**Comment by littabird** [comment]
> should be fixed with this patch

**Where is the patch?**

**Comment by Frenzie** [comment]
You can see the changes if you click on "files changed" at the top of the PR.

**Comment by littabird** [comment]
Thanks for getting back to me,  Frans

> You can see the changes if you click on "files changed" at the top of the PR

I don't understand at all.
- Where is the button for "files changed" ? And why do I need to do this?
(I got cloudfare issue -- their Rocket Load is having conflict with your
javascript).
- What is "PR"?

Ted

**Comment by Frenzie** [comment]
It'll take you to this link: https://github.com/FreshRSS/FreshRSS/pull/1809/files

PR stands for pull request. ^_^

**Comment by littabird** [comment]
> It'll take you to this link: https://github.com/FreshRSS/FreshRSS/pull/1809/files
> PR stands for pull request. ^_^

Thanks for being patient with a coding retard like me. Appreciated.

1. Am I supposed to copy and paste all the followings (onto app/Models/Auth.php)? Or just some of them?

@@ -63,7 +63,6 @@ private static function accessControl() {
			$login_ok = $current_user != '';
			if ($login_ok) {
				Minz_Session::_param('currentUser', $current_user);
				Minz_Session::_param('REMOTE_USER', $current_user);
			}
			return $login_ok;
		case 'none':
@@ -102,6 +101,7 @@ public static function giveAccess() {
		}

		Minz_Session::_param('loginOk', self::$login_ok);
		Minz_Session::_param('REMOTE_USER', httpAuthUser());
	}

	/**
@@ -133,6 +133,7 @@ public static function removeAccess() {
		self::$login_ok = false;
		Minz_Session::_param('loginOk');
		Minz_Session::_param('csrf');
		Minz_Session::_param('REMOTE_USER');
		$system_conf = Minz_Configuration::get('system');

		$username = '';

2. I believe this "@@ -63,7 +63,6 @@ private static" is to be stripped off (never seen such code before)?

Actually, the issue is bigger than LOGIN, I found out Javascript of the whole site will be deactivated as soon as Cloudfare's Rocket Loader™ is switched on, which I have to becos the main site is on Cloudfare (FreshRSS is on subdomain)

3.  Incompatibility With Cloudfare's Rocket Loader™

You can see the problem here http://bon.bonology.com/p/i/  (Anonymous Viewing)

- Rocket Loader™ is needed for teh main site becos https://support.cloudflare.com/hc/en-us/articles/200168056-What-does-Rocket-Loader-do-

Appreciate it greatly if you can help to resolve the conflict... It seems there is solution >

If you have a Content Security Policy, you will need to update it to allow Rocket Loader to run: What is Content Security Policy (CSP), and how can I use it with Cloudflare?
https://support.cloudflare.com/hc/en-us/articles/216537517-What-is-Content-Security-Policy-CSP-and-how-can-I-use-it-with-Cloudflare-

Awaiting  with thanks.

**Comment by Frenzie** [comment]
The lines in red with a - are removed, the ones in green with a + are added. (So 1 line removed, 2 added.)

<del>But as @Alkarex said you could also just wait a few days for the 1.10.1 bugfix release.</del><ins>This is from years ago, my bad.</ins>

**Comment by littabird** [comment]
> wait a few days for the 1.10.1 bugfix release

I didn't know there is a new release. You see, one thing you programming gurus do not see is we coding retards do not see things from your perspective... eg. I have no clue what is PR etc. It's for this reason I do not hang around in programmer forum as I feel their joints are kinda "complicated" (need some coaching to get around).
 
Yeah, I might as well wait for that... I will play with it to see the fix is any good before deleting the install.

**Comment by Frenzie** [comment]
Sorry, I'm not interested.

**Comment by littabird** [comment]
*Is there something in FreshRSS blocking embedded images or javascript from
showing up on the frontpage (the one after login page)?*

I pasted an image and sample javascript on both index.html and index.php (I
have no clue which is the page)... Nothing happens and then I saw the image
whenever the site is loading up, just to disappear after loaded up.
So, I imagine there must be some ads blocker type of script built in?
Is there a way to insert something into the display pages? (I just wanted
to insert a banner and pop up notification scripts becos i intend to allow
anonymous reading).

**Comment by littabird** [comment]
> The lines in red with a - are removed, the ones in green with a + are added. (So 1 line removed, 2 added.)
> 
> ~But as @Alkarex said you could also just wait a few days for the 1.10.1 bugfix release.~This is from years ago, my bad.

Ah, so there nothing new?
What do I do then?
Do I just copy and paste this (as extra) https://github.com/FreshRSS/FreshRSS/pull/1809/files ... **do I need to delete anything?**

Pls. help with the image embed problem not showing up here https://github.com/FreshRSS/FreshRSS/pull/1809#issuecomment-841447606

**Comment by Alkarex** [comment]
@littabird This patch has been included in FreshRSS since version 1.10.1. Just make sure you have the latest FreshRSS version (currently 1.18.0). See our release history: https://github.com/FreshRSS/FreshRSS/releases

**Comment by littabird** [comment]
Thanks Alexandre Alapetite.

1. INCOMPATIBLE WITH CLOUFARE

I just checked, mine is Version: 1.18.0... That means I am out of luck
because FreshRSS has conflict with Cloudfare's Rocket Load --- they prevent
your javascript from loading (I could even press the login button, or if I
have it set to anonymous viewing, I wouldn't be able even to open the
entries , javascript just wouldn't work (unless I switch off the Rocket
Load... But I need this for the main site.

Do you have any idea what I can do?

2. IMAGE/JAVASCRIPT BLOCKING?

Another thing *Is there something in FreshRSS blocking embedded image or
forbidding javascript from running on the frontpage (the login page or the
one after login page)?*

I pasted an image and a sample javascript on both index.html and index.php
(I have no clue which is the frontpage)... Nothing happens but I did see
the image (after the FreshRSS image) popped up whenever the site was
loading up, just to disappear after loadied up.

So, I imagine there must be some blocker script in FreshRSS?

Is there a way to insert something to display? (I just wanted to insert a
banner and perhaps also display notifications).

Or can you consider releasing an *open web version* (basically the same
thing except no sign in is necessary... Everything else is a bonus) -- I am
confident FreshRSS can become very popular as an open website. So, please
help.

Ted

**Comment by Alkarex** [comment]
See https://github.com/FreshRSS/FreshRSS/issues/3617#issuecomment-841795350

**Pull request merged**
