### PR TITLE
Fix extension hook for updated articles

### PR DESCRIPTION
**Pull request by Alkarex**
https://github.com/FreshRSS/FreshRSS/issues/1926

### CODE REVIEW

**Comment by Frenzie** [comment]
Looks good at a glance, no time to test atm. :-)

**Comment by kevinpapst** [comment]
Was that call removed in the last version? 
Looks good, I will test it as soon as I can.

**Comment by Alkarex** [comment]
@kevinpapst Not that I can remember, and not according to the quick history check I have done

**Comment by Alkarex** [comment]
I think there is a remaining bug for PubSubHubbub updates (for which the extensions do not seem to be loaded). Will look at it tonight

**Comment by Alkarex** [comment]
Extensions in PubSubHubbub fix attempt https://github.com/FreshRSS/FreshRSS/pull/1932/commits/8d09e4f85bb150d9a0261c13e176b5249105929b

**Pull request merged**
