### PR TITLE
FreshRSS 1.14.1

### PR DESCRIPTION
**Pull request by Alkarex**
The big changes / refactoring in the [version 1.14.0](https://github.com/FreshRSS/FreshRSS/pull/2298) released on Sunday introduced a number of bugs, requiring a [quick minor release 1.14.1](https://github.com/FreshRSS/FreshRSS/milestones/1.14.1).

Please help checking the /dev branch thoroughly so can we release it on Saturday :-)

Full [changelog](https://github.com/FreshRSS/FreshRSS/blob/dev/CHANGELOG.md):

* Bug fixing (regressions introduced in 1.14.0)
	* Fix *load more articles* when using ascending order [#2314](https://github.com/FreshRSS/FreshRSS/issues/2314)
	* Fix cron in the Ubuntu flavour of the Docker image [#2319](https://github.com/FreshRSS/FreshRSS/issues/2319)
	* Fix the use of arrow keyboard keys for shortcuts [#2316](https://github.com/FreshRSS/FreshRSS/issues/2316)
	* Fix control+click or middle-click for opening articles in a background tab [#2310](https://github.com/FreshRSS/FreshRSS/issues/2310)
	* Fix the naming of the option to unfold categories [#2307](https://github.com/FreshRSS/FreshRSS/issues/2307)
	* Fix shortcut problem when using unfolded articles [#2328](https://github.com/FreshRSS/FreshRSS/issues/2328)
	* Fix auto-hiding articles [#2323](https://github.com/FreshRSS/FreshRSS/issues/2323)
	* Fix scroll functions with Edge [#2337](https://github.com/FreshRSS/FreshRSS/pull/2337)
	* Fix drop-down menu warning [#2353](https://github.com/FreshRSS/FreshRSS/pull/2353)
	* Fix delay for individual mark-as-read actions [#2332](https://github.com/FreshRSS/FreshRSS/issues/2332)
	* Fix scroll functions in Edge [#2337](https://github.com/FreshRSS/FreshRSS/pull/2337)
* Bug fixing (misc.)
	* Fix extensions in Windows [#994](https://github.com/FreshRSS/FreshRSS/issues/994)
	* Fix import of empty articles [#2351](https://github.com/FreshRSS/FreshRSS/pull/2351)
	* Fix quote escaping on CLI i18n tools [#2355](https://github.com/FreshRSS/FreshRSS/pull/2355)
* UI
	* Better handling of bad Ajax requests and fast page unload (ask confirmation) [#2346](https://github.com/FreshRSS/FreshRSS/pull/2346)
* I18n
	* Improve Dutch [#2312](https://github.com/FreshRSS/FreshRSS/pull/2312)
* Misc.
	* Check JavaScript (jshint) in Travis continuous integration [#2315](https://github.com/FreshRSS/FreshRSS/pull/2315)
	* Add PHP 7.3 to Travis [#2317](https://github.com/FreshRSS/FreshRSS/pull/2317)

### CODE REVIEW

**Comment by Alkarex** [comment]
@Bedeau69 @Pitel @Tealk @krispek @Balooforever @Liandriz @thomasrenes @Massedil @techexo @oupala @ggdagg etc. :-)

**Comment by Tealk** [comment]
Thanks again for the quick help.
Up to now it looks quite good only the long wait is still present.

**Comment by Tealk** [comment]
@Alkarex 
I noticed that the articles marked as read do not remain marked as read. Those I open with the middle mouse button.

**Comment by Alkarex** [comment]
@Tealk Huuuum, could you please open a new issue (and explain a bit more if possible)?

**Comment by Massedil** [comment]
I've updated to the latest dev version and let you know if something does not works as expected. For me now, my problem #2314 is solved.

**Review by Frenzie — DISMISSED** [review]

**Comment by oupala** [comment]
I'm afraid it still does not work for me.

When I click on the *read* envelope, it passes from red to grey, and nothing else happens.

Here what I've found in the web console:

```
TypeError: json is null
main.js:213:1
send_mark_read_queue/req.onload
https://example.com/FreshRSS/p/scripts/main.js:213:1
```

**Comment by Alkarex** [comment]
@oupala Please open a new ticket with your case, with some info about your configuration and options

**Comment by oupala** [comment]
@Alkarex see #2345.

**Comment by Alkarex** [comment]
A bunch of additional fixes and improvements have landed in the /dev branch, and it looks like we are done for 1.14.1. Additional testing welcome before the release!

**Comment by aledeg** [comment]
good job! :tada:

**Comment by oupala** [comment]
As far as I tested, the scroll bug is fixed. But when I click on the enveloppe to mark it as read, it does not disappear. When I scroll down a little bit, then it disappear. But the rule for disappearing is not clear as it seems that if the first article is marked as read, it does not disappear.

So I don't know if the behavior is as expected or not.

Thanks anyway for the responsive work!

**Comment by thomasrenes** [comment]
Looks good to me! Haven't noticed any issues with the `/dev` branch so far.

**Comment by oupala** [comment]
Thanks for this fix-release.

I think we should all be more involved in the next release preview. We should try to test more the next RCs (release candidate) so that the 1.15.0 is not the one that everyone install and discover bugs that should have been discovered in 1.15.0-RClast.

I'll try to test the 1.15.0-RC when it will be available.

**Comment by Alkarex** [comment]
@oupala Indeed, and you are more than welcome. I would also like to say that it is OK-safe to run the /dev branch (this is what I do myself), which can be seen as a kind of rolling release. Patches merged into /dev have already been tested to some extent.

**Comment by techexo** [comment]
Thanks @Alkarex for the fix release, my problems are gone :)

**Pull request merged**
