### PR TITLE
Add navigation to about page

### PR DESCRIPTION
**Pull request by math-GH**
The "About" page has no navigation. It is only available via the dropdown menu (and via the login screen)

Changes proposed in this pull request:
- add the configuration aside navigation to "about" page. It is now available in the configuration menu (for normal users and for admin users)
- the about page via the login screen does not changed (no navigation aside)

grafik

How to test the feature manually:
go to the "about" page

Pull request checklist:
- [x] clear commit messages
- [x] code manually tested

### CODE REVIEW

**Comment by aledeg** [comment]
By doing such thing, you are breaking the menu. I mean that the about page is separated from the administration section in the menu, not in your modification. It can be confusing.

**Comment by Alkarex** [comment]
> By doing such thing, you are breaking the menu. I mean that the about page is separated from the administration section in the menu, not in your modification. It can be confusing.

I think just adding a line separator could be enough.

Waiting for https://github.com/FreshRSS/FreshRSS/pull/3803 to be merged first

**Comment by aledeg** [comment]
That's what I had in mind!

**Comment by math-GH** [comment]
> I think just adding a line separator could be enough.
> 

What do you think about an empty lightgrey line?
grafik

**Comment by Alkarex** [comment]
> What do you think about an empty lightgrey line?

Fine for me 👍🏻

**Pull request merged**
