### PR TITLE
Use HTML autocomplete new-password

### PR DESCRIPTION
**Pull request by Alkarex**
https://github.com/FreshRSS/FreshRSS/issues/1841#issuecomment-376551901
autocomplete="new-password" for user management pages

https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

**Comment by kevinpapst** [comment]
> though support for this has not been implemented in all browsers yet

I did not check the documentation of all alternative browsers, but:
when considering the browser market-share I would vote for sticking with an attribute that works in ALL browsers.

**Comment by Alkarex** [comment]
Thanks to the way unknown values for this parameter are processed, this
change is supposed to be fine in all browsers. And for sure, the previous
"off" value is very problematic in Firefox, and problematic in Chrome.
In any case, tests welcome 🤓

>

**Comment by kevinpapst** [comment]
:D so the fallback for invalid/unknown values is always "off"?

**Comment by Alkarex** [comment]
@kevinpapst Apparently yes, and an even stronger "off" than the real "off".

**Comment by Alkarex** [comment]
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9847360/

**Comment by Alkarex** [comment]
Let's continue the testing in /dev to have a broader audience

**Comment by Alkarex** [comment]
Follow up of https://github.com/FreshRSS/FreshRSS/issues/880
https://github.com/FreshRSS/FreshRSS/pull/881

**Pull request merged**
