### PR TITLE
FreshRSS 1.14.3

### PR DESCRIPTION
**Pull request by Alkarex**
Hello,
Before some more substantial changes scheduled for 1.15.0, let's [release a version 1.14.3](https://github.com/FreshRSS/FreshRSS/milestones/1.14.3) before the summer vacations 🏖️ with a number of small improvements and bug fixes. In particular, there is now a Docker image automatically built for ARM (e.g. Raspberry Pi) testable with [`freshrss/freshrss:dev-arm`](https://hub.docker.com/r/freshrss/freshrss/tags).

Thanks to the 12 contributors, especially newcomers @rosiel , @lx-s , @Sp3r4z , @Fake4d , @SuperSandro2000, and @rnc :-)

Full [changelog](https://github.com/FreshRSS/FreshRSS/blob/dev/CHANGELOG.md):

* Bug fixing
	* Fix wrong mark-as-read limit [#2429](https://github.com/FreshRSS/FreshRSS/issues/2429)
	* Fix API call for removing a category [#2411](https://github.com/FreshRSS/FreshRSS/issues/2411)
	* Fix user self-registration [#2381](https://github.com/FreshRSS/FreshRSS/issues/2381)
	* Make CGI Authorization configuration for API more compatible [#2446](https://github.com/FreshRSS/FreshRSS/issues/2446)
	* Fix refresh icon in Swage theme [#2375](https://github.com/FreshRSS/FreshRSS/issues/2375)
	* Fix message banner in Swage theme [#2379](https://github.com/FreshRSS/FreshRSS/issues/2379)
	* Docker: Add `php-gmp` for API support in Ubuntu 32-bit [#2450](https://github.com/FreshRSS/FreshRSS/pull/2450)
* UI
	* New configuration page for each category [#2369](https://github.com/FreshRSS/FreshRSS/issues/2369)
	* Update shortcut configuration page [#2405](https://github.com/FreshRSS/FreshRSS/issues/2405)
	* CSS style for printing [#2149](https://github.com/FreshRSS/FreshRSS/issues/2149)
	* Do not hide multiple `<br />` tags [#2437](https://github.com/FreshRSS/FreshRSS/issues/2437)
	* Updated to jQuery 3.4.1 (only for statistics page) [#2424](https://github.com/FreshRSS/FreshRSS/pull/2424)
* Deployment
	* Docker: Add automatic health check [#2438](https://github.com/FreshRSS/FreshRSS/pull/2438)
	* Docker: Add a version for ARM architecture such as for Raspberry Pi [#2436](https://github.com/FreshRSS/FreshRSS/pull/2436)
	* Docker: Ubuntu image updated to 19.04 with PHP 7.2.19 and Apache 2.4.38 [#2422](https://github.com/FreshRSS/FreshRSS/pull/2422)
	* Docker: Alpine image updated to 3.10 with PHP 7.3.7 and Apache 2.4.39 [#2238](https://github.com/FreshRSS/FreshRSS/pull/2238)
* Security
	* Allow `@-` as valid characters in usernames (i.e. allow most e-mails) [#2391](https://github.com/FreshRSS/FreshRSS/issues/2391)
* I18n
	* Improve Occitan [#2358](https://github.com/FreshRSS/FreshRSS/pull/2358)
* Misc.
	* New parameter `?maxFeeds=10` to control the max number of feeds to refresh manually [#2388](https://github.com/FreshRSS/FreshRSS/pull/2388)
	* Default to SQLite during install [#2443](https://github.com/FreshRSS/FreshRSS/pull/2443)

### CODE REVIEW

**Comment by Alkarex** [comment]
By the way, if anybody has any idea about the following Docker Hub issues, please tell :-) :

1. How to use this specific readme file https://github.com/FreshRSS/FreshRSS/blob/master/Docker/README.md on https://hub.docker.com/r/freshrss/freshrss . I have tried with a post_checkout hook but without success:

https://github.com/FreshRSS/FreshRSS/blob/0a297addc060692f163c2614aa9989f5840f494a/Docker/hooks/post_checkout#L4

2. When cross-compiling for ARM on Docker Hub, and while waiting for Docker Hub to support the `--squash` option, how to avoid having 2 copies of `qemu-arm-static` (we should have zero) in the final image layers?

https://github.com/FreshRSS/FreshRSS/blob/0a297addc060692f163c2614aa9989f5840f494a/Docker/Dockerfile-QEMU-ARM#L59

3. When cross-compiling for ARM on Docker Hub, and while waiting for Docker Hub to support the `--platform` parameter, how to produce an ARM image with the proper metadata, i.e. `arm` and not `amd64`

```sh
sudo docker inspect --format='{{.Architecture}}' freshrss/freshrss:dev-arm
amd64
```

**Comment by SuperSandro2000** [comment]
1. Is the readme in the same dir as the dockerfile you build?

2. I use balenas cross compile images but they have the qemu build in, too.
And combining all RUNs would work but it would destroy caching.

3. I don't know if docker cloud supports it but you can do it manually and puhs it to docker hub. I do this with my multi Arch manifest images. Let me know if you want to know the details.

**Comment by Alkarex** [comment]
@SuperSandro2000 Yes for 1, you can see https://github.com/FreshRSS/FreshRSS/tree/master/Docker/
Ok for the rest, and yes, I know how to manually push for multiple architectures, but it is nice to have everything automated.

**Comment by SuperSandro2000** [comment]
1. It might be that it needs to be lower cased after the first letter https://github.com/docker/hub-feedback/issues/300#issuecomment-138974087
3. I do it like this: I create the manifest, tag them correctly and then push the manifest together with the other images into the repo. Then docker pull chooses the right image for your architecture. See https://github.com/SuperSandro2000/docker-images/blob/master/zeronet/push.sh#L29 and https://hub.docker.com/r/supersandro2000/zeronet/tags
2. And this would be solved, too if you would switch to travis or circleci or some other CI that allows you to run commands outside the Dockerfile.

**Comment by Alkarex** [comment]
@SuperSandro2000 Yes, I also have some repositories where I push two versions and a manifest. On Docker Hub, it is also possible to run commands outside the Docker file https://docs.docker.com/docker-hub/builds/advanced/ (see the various hooks); I am just not sure which command :-)

**Comment by SuperSandro2000** [comment]
I didn't know these hooks existed. Learning something new every day.

**Comment by SuperSandro2000** [comment]
Btw I saw you wanted to add hadolint.
I would suggest this config https://github.com/SuperSandro2000/docker-images/blob/master/.hadolint.yaml of me and this install script of me https://github.com/SuperSandro2000/docker-images/blob/master/.travis.yml#L58 https://github.com/SuperSandro2000/docker-images/blob/master/.travis.yml#L61 .

**Pull request merged**
