### PR TITLE
Remove superflous SQL category request

### PR DESCRIPTION
**Pull request by Alkarex**
A category request was systematically done, although it is not always
needed.

### CODE REVIEW

**Comment by Alkarex** [comment]
Especially needed now that the number of "mark as read" requests will increase with "scroll as read" https://github.com/FreshRSS/FreshRSS/pull/1309

**Comment by Alwaysin** [comment]
What did motivate the choice of a default "mark read as scroll"? I think this is a bad idea.

**Comment by Alkarex** [comment]
It is an option, so you can turn it off. The main reason is to address the UI problem of marking previous articles as read, for which there is currently no other option in FreshRSS https://github.com/FreshRSS/FreshRSS/issues/329

**Comment by Alwaysin** [comment]
Yes I've turned it off, I just find it very disturbing when you first install an rss reader that it marks the articles as read directly, when you usually go around and scroll to see how it looks. You may think this is a bug.

**Pull request merged**
