### PR TITLE
FreshRSS 1.15.1

### PR DESCRIPTION
**Pull request by Alkarex**
Quick release of [FreshRSS 1.15.1](https://github.com/FreshRSS/FreshRSS/milestones/1.15.1) for some fixes following [FreshRSS 1.15.0](https://github.com/FreshRSS/FreshRSS/milestones/1.15.0) (https://github.com/FreshRSS/FreshRSS/pull/2599).

Full [changelog](https://github.com/FreshRSS/FreshRSS/blob/dev/CHANGELOG.md):

* Features
	* New approach based on OPML to definite default feeds for new users [#2627](https://github.com/FreshRSS/FreshRSS/pull/2627)
* API
	* Always send articles IDs as string, to fix compatibility with Reeder [#2621](https://github.com/FreshRSS/FreshRSS/pull/2621)
* Bug fixing (regressions from 1.15.0)
	* Fix database auto-creation at install [#2635](https://github.com/FreshRSS/FreshRSS/pull/2635)
	* Fix bug in database size estimation with PostgreSQL for users with uppercase names [#2631](https://github.com/FreshRSS/FreshRSS/pull/2631)
	* Reset name of default category (which cannot be customised anymore) [#2638](https://github.com/FreshRSS/FreshRSS/pull/2638)
	* Fix UI style details [#2634](https://github.com/FreshRSS/FreshRSS/pull/2634)
* Security
	* Improve cookie security with policy `SameSite=Lax` [#2630](https://github.com/FreshRSS/FreshRSS/pull/2630)
* Misc.
	* Perform automatic git updates with safer fetch+reset instead of clean+fetch+merge [#2625](https://github.com/FreshRSS/FreshRSS/pull/2625)

### CODE REVIEW

**Review by aledeg — DISMISSED** [review]

**Review by Frenzie — DISMISSED** [review]
Didn't test everything but I spot no regressions.

**Comment by Alkarex** [comment]
Here we are, ready to release. Any last comment?

**Review by Frenzie — DISMISSED** [review]
Nothing changed from my perspective.

**Comment by Alkarex** [comment]
Hum, actually, I do not like https://github.com/FreshRSS/FreshRSS/pull/2638 after all, because it will not fix the issue for people already using 1.15.0. New fix coming, sorry

**Comment by Alkarex** [comment]
NOW it should be good :-)

**Pull request merged**
