### PR TITLE
Newsboat support

### PR DESCRIPTION
**Pull request by PetraOleum**
Newsboat is a feed reader for the unix-derived terminal, and is the successor to Newsbeuter. FreshRSS support has been [merged into master](https://github.com/newsboat/newsboat/commit/f18145fc98700178429cbd137e0309f89ec89d5b) but there has not yet been a release since then. In the meantime I've created this pull request that can be merged whenever it becomes strictly accurate.

I've filled out the table to the best of my ability, but I'm not completely clear on what "Fast sync" and "Fetch more in individual views" mean.

Newsboat should presumably be also added to list in `docs/en/users/06_Mobile_access.md`

Changes proposed in this pull request:

- Add "newsboat" to list of apps in readme
-
-

How to test the feature manually:

1. View readme
2.
3.

Pull request checklist:

- [x] clear commit messages
- [ ] code manually tested
- [ ] unit tests written (optional if too hard)
- [x] documentation updated

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

**Comment by Minoru** [comment]
Newsboat maintainer here :wave: Hi Petra :) Just wanted to make a note and ask a few questions.

> FreshRSS support has been merged into master but there has not yet been a release since then.

Newsboat releases come out every three months, the next one is going to be on June 20th (give or take a few days). That'll include FreshRSS support. I guess the table can say "Newsboat 2.24+" to clarify that.

My few questions are:

* there are a checkmark in the "works offline" column, but Newsboat can't actually work *with FreshRSS* offline, it won't even start. It *can* be used as a standalone reader, and it *can* work offline in that mode, but that's probably of no interest to FreshRSS users. Do I misunderstand the meaning of that checkmark?
* there's a minus sign in the "Labels" column, but Newsboat does support FreshRSS categories (presenting them as Newsboat tags). Are categories different from labels?

**Comment by Frenzie** [comment]
> there are a checkmark in the "works offline" column, but Newsboat can't actually work with FreshRSS offline, it won't even start. It can be used as a standalone reader, and it can work offline in that mode, but that's probably of no interest to FreshRSS users. Do I misunderstand the meaning of that checkmark?

No, I don't think so. That should be either a minus or something like "not with FreshRSS" then.

> there's a minus sign in the "Labels" column, but Newsboat does support FreshRSS categories (presenting them as Newsboat tags). Are categories different from labels?

Yes, labels are something users can add to individual entries.

**Comment by PetraOleum** [comment]
> No, I don't think so. That should be either a minus or something like "not with FreshRSS" then.

Yeah, I forgot that it needs to connect every time, sorry!

**Comment by Alkarex** [comment]
Related PR https://github.com/newsboat/newsboat/pull/1559
@PetraOleum Thanks, nice work. Did you spot any missing part for your needs in the FreshRSS implementation of the Google Reader API? Or notable differences with other implementations?

**Comment by Alkarex** [comment]
@PetraOleum I have just tried the master branch of Newsboat:

image

The first connection looks fine, just like the reception of the list of feeds. However, I get an error after that and all feeds are at zero unread articles.

I only got two requests to the server:

```
172.X.X.X - - [08/Apr/2021:16:36:24 +0200] "POST /api/greader.php/accounts/ClientLogin HTTP/1.1" 200 111 "-" "Newsboat/r2.23-70-gf5fdd (Linux x86_64)"
172.X.X.X - - [08/Apr/2021:16:36:24 +0200] "GET /api/greader.php/reader/api/0/subscription/list?output=json HTTP/1.1" 200 9989 "-" "Newsboat/r2.23-70-gf5fdd (Linux x86_64)"
```

Can you double-check against the latest master of Newsboat and latest edge branch of FreshRSS?

I will look again a bit later.

**Comment by Minoru** [comment]
@Alkarex By default, Newsboat doesn't refresh feeds on startup. Press `R` to reload them all, then the counts will change. Alternatively, you can start with `newsboat -r`, or add [`refresh-on-startup yes`](https://newsboat.org/releases/2.23/docs/newsboat.html#refresh-on-startup) to your config ;)

**Comment by Alkarex** [comment]
@Minoru Thanks!

I an trying to find whether it is possible to mark articles as read/unread, favourites (starred) but without luck so far (I tried "bookmarking", but that is not the same apparently - not saved back to the server). Any tip? Sorry for the newbie questions :-P

**Comment by Minoru** [comment]
> whether it is possible to mark articles as read/unread

Items are marked read when you open them. You can also toggle the status by pressing `N` while in the article list (i.e. inside the feed).

> favourites (starred)

Add `freshrss-flag-star "s"` to the config, start Newsboat, go to the article list or article view, press `^E` (`Ctrl` and `e` simultaneously), type `s` then press `Enter`. That'll star the item. To remove the star, press `^E` again and remove the `s`, then press `Enter`.

> I tried "bookmarking", but that is not the same apparently - not saved back to the server

Yeah, that calls a user-specified script locally, and can be used to e.g. post links to Mastodon or save them to del.icio.us.

Questions are fine. Happy that you're checking this PR so meticulously ^_^

**Comment by Alkarex** [comment]
@PetraOleum I have added more references to Newsboat in the doc.

**Comment by PetraOleum** [comment]
Thanks for the merge and the extra doc!

> Did you spot any missing part for your needs in the FreshRSS implementation of the Google Reader API? Or notable differences with other implementations?

Newsboat actually already had a greader api integration targeted at FeedHQ, however this did not work with FreshRSS because it expected an `/atom/` api endpoint for downloading the contents of the feeds: FreshRSS seems to only want to return json data. I don't know which is the "pure" greader api behaviour (does that even make sense any more?) but it might be worth looking into.

**Pull request merged**
