### PR TITLE
Take advantage of PHP 5.4+ short echo

### PR DESCRIPTION
**Pull request by Alkarex**
https://php.net/migration54.new-features thanks to https://github.com/FreshRSS/FreshRSS/pull/2495

Use `<?=  $x ?>` instead of `<?php echo $x; ?>`
10kB of code saved :-)

Done with regular expression:
```
<\?php echo (.+?);? *\?>
<?= \1 ?>
```

### CODE REVIEW

**Comment by Alkarex** [comment]
Arg, that will need to be explained to Travis. Could you please have a look @Frenzie ?

**Comment by Frenzie** [comment]
Can't test atm but I figure just removing this line should do the trick. 

https://github.com/FreshRSS/FreshRSS/blob/82611c9622ed23b0e9fcf5f9f651ddffa1fd7706/phpcs.xml#L48

**Comment by marienfressinaud** [comment]
Nice, that's something I wanted from a long time :) Did you use `sed` to automate the change in all files?

**Comment by Alkarex** [comment]
Yes

**Comment by Alkarex** [comment]
Travis fixed https://github.com/FreshRSS/FreshRSS/pull/2585/commits/299bc7d34e5e1d7fc95f50585e4d3c38eed0504c

**Pull request merged**
