### PR TITLE
Fix CSS hover long title

### LINKED ISSUE #2755: Item title is difficult to read on hover
Hi!

Since the last version the item's title is wider and overlaps the date on hover.
But the background being transparent I find it quite difficult to read on small screens:

image

Maybe the background could go over the date or something?

Thanks for the hardwork, as always.

### PR DESCRIPTION
**Pull request by Alkarex**
#fix https://github.com/FreshRSS/FreshRSS/issues/2755

### CODE REVIEW

**Comment by Alkarex** [comment]
Fixed for all themes except Ansum and Mapco for which the bug https://github.com/FreshRSS/FreshRSS/issues/2755 is still visible. Help welcome. Ping @patjennings if you are around :-)

**Comment by Alkarex** [comment]
I found the (nasty!) reason for the issue with Ansum and Mapco themes https://stackoverflow.com/questions/2837057/what-has-bigger-priority-opacity-or-z-index-in-browsers

**Comment by Alkarex** [comment]
All done

**Comment by Alkarex** [comment]
Let's test a bit more in master before the release

**Comment by Alkarex** [comment]
Damn, there is still a little bug for read articles in "Blue Lagoon" and "Screwdriver" themes...

**Comment by Alkarex** [comment]
Edit: updated themes names in my comment above

**Comment by batchennings** [comment]
> I found the (nasty!) reason for the issue with Ansum and Mapco themes https://stackoverflow.com/questions/2837057/what-has-bigger-priority-opacity-or-z-index-in-browsers

Thanks @Alkarex . I wasn't around, sorry for that. Nothing more to contribute, but i will stay in touch for future improvements.

**Comment by Alkarex** [comment]
@patjennings No worries, and please double-check your themes, as I hope I have broken something else. The issue was a bit more complicated than I had anticipated, and not due to the exact same bug in all themes... If you are interested, the main culprit was due to the combination of `position` and `opacity` https://stackoverflow.com/questions/2837057/what-has-bigger-priority-opacity-or-z-index-in-browsers

**Pull request merged**
