### PR TITLE
Fix SQL constraint insert into entrytmp table

### PR DESCRIPTION
**Pull request by Alkarex**
https://github.com/FreshRSS/FreshRSS/issues/1614

### CODE REVIEW

**Comment by Alkarex** [comment]
@Trim Could you please test this patch?

**Comment by Frenzie** [comment]
@Trim in #1614 you mentioned you ran "a test". Would that be anything that could be put in unit test form to prevent regressions?

**Comment by Alkarex** [comment]
@Frenzie Related https://github.com/FreshRSS/FreshRSS/issues/1639

**Comment by Alkarex** [comment]
Thanks for the feedback.
For the record, I am considering changing our fallback mechanism for feeds without GUID to something like hash(link + title) instead of only link; and if there is no link, then use the default SimplePie hash.

**Pull request merged**
