### PR TITLE
Add a subscription tools page

### PR DESCRIPTION
**Pull request by aledeg**
See #1354

It's missing translations. Only English and French are available.
Contributions wanted.

### CODE REVIEW

**Comment by Alkarex** [comment]
Could you please add a `  //TODO` at the end of each line that requires translation?
Example: https://github.com/FreshRSS/FreshRSS/blob/f7ad1703beb2ff9439ca7c3647e0fb55cfd512dc/app/i18n/it/conf.php#L96

**Comment by aledeg** [comment]
Sure

**Comment by aledeg** [comment]
Done

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/commit/ef80a3be8d6fededb13b698f8e20ec9d4ce7bb8d

**Pull request merged**
