### PR TITLE
i18n Korean

### PR DESCRIPTION
**Pull request by sjeon87**

### CODE REVIEW

**Comment by Frenzie** [comment]
Thanks! The script says there are still a couple missing btw? :-)

> kr    - Translation is  96.9% complete.

**Comment by sjeon87** [comment]
@Frenzie In which case the script says translation is not complete? It seems I translated all items commented with `todo`. And left things like *Facebook* as-is (also added it in `ignore.php`)

**Comment by sjeon87** [comment]
```txt
> php check.translation.php -l=kr -d
Language: kr
Untranslated key gen.date.Apr - \A\p\r\i\l
Untranslated key gen.date.Aug - \A\u\g\u\s\t
Untranslated key gen.date.Dec - \D\e\c\e\m\b\e\r
Untranslated key gen.date.Feb - \F\e\b\r\u\a\r\y
Untranslated key gen.date.Jan - \J\a\n\u\a\r\y
Untranslated key gen.date.Jul - \J\u\l\y
Untranslated key gen.date.Jun - \J\u\n\e
Untranslated key gen.date.Mar - \M\a\r\c\h
Untranslated key gen.date.May - \M\a\y
Untranslated key gen.date.Nov - \N\o\v\e\m\b\e\r
Untranslated key gen.date.Oct - \O\c\t\o\b\e\r
Untranslated key gen.date.Sep - \S\e\p\t\e\m\b\e\r
Untranslated key gen.lang.oc - Occitan
Untranslated key gen.pagination.first - First
Untranslated key gen.pagination.last - Last
Untranslated key gen.pagination.next - Next
Untranslated key gen.pagination.previous - Previous
Untranslated key gen.share.linkedin - LinkedIn
Untranslated key gen.share.pinboard - Pinboard
Untranslated key gen.share.pocket - Pocket
Untranslated key gen.short.by_author - By:
Untranslated key gen.short.ok - Ok!
```

Got it. will fix it.

**Comment by Frenzie** [comment]
Thanks!

**Pull request merged**
