### PR TITLE
Updated japanese translation

### PR DESCRIPTION
**Pull request by ghost**
Changes proposed in this pull request:

- Updated japanese translation #3898 

How to test the feature manually:

1.Run make test

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
Looks good, but I think you may have missed the one string with an untranslated part? (Sorry, on phone atm so can't link)

**Comment by ghost** [comment]
> Looks good, but I think you may have missed the one string with an untranslated part? (Sorry, on phone atm so can't link)

Which name of the file has not been translated?

**Comment by Frenzie** [comment]
My bad, I meant <https://github.com/FreshRSS/FreshRSS/pull/4024>. This PR just coincidentally came right after, and I incorrectly assumed it was in response.

In some languages `You can try force adding by appending <code>#force_feed</code> to the URL.` is missing, but Japanese isn't one of them.

**Comment by math-GH** [comment]
@312k Thank you very much for the very quick response and creating this PR :)

**Pull request merged**
