### PR TITLE
Fix tag management translation

### PR DESCRIPTION
**Pull request by aledeg**
Changes proposed in this pull request:

- Translate feedback messages when managing tags.

How to test the feature manually:

1. open the tag management page,
2. create or rename tags,
3. check feedback messages.

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested
- [ ] unit tests written (optional if too hard)
- [ ] documentation updated

[Additional information can be found in the documentation](https://github.com/FreshRSS/FreshRSS/tree/master/docs/en/developers/04_Pull_requests.md).

### CODE REVIEW

**Review by Alkarex — APPROVED** [review]

**Comment by Alkarex** [comment]
Looks good. Renaming a tag to an existing one merges them - which I think is fine.

**Comment by aledeg** [comment]
I haven't modified how it behaves. I've only added the translation.

**Comment by Frenzie** [comment]
> Renaming a tag to an existing one merges them - which I think is fine.

Didn't check what it does in this PR, but from a UI perspective a warning might not be a bad idea?

**Comment by aledeg** [comment]
@Frenzie A pop-up appears when you valid the action.

**Pull request merged**
