### PR TITLE
TT-RSS import

### PR DESCRIPTION
**Pull request by Alkarex**
Import of Tiny Tiny RSS favourites from a file like `TinyTinyRSS_exported_2018-10-24.xml`
https://github.com/FreshRSS/FreshRSS/issues/2018#issuecomment-432710462
https://github.com/FreshRSS/FreshRSS/issues/2079

### CODE REVIEW

**Comment by Alkarex** [comment]
@typhoe for you :-)
Tests welcome (I have only quickly tested myself).
I have not implemented the import of custom labels yet. It does not look like it is something you use, do you?

**Comment by Alkarex** [comment]
P.S. If you have an example of export with custom labels, I am interested.

**Comment by Alkarex** [comment]
@typhoe I have added the ability to import custom labels as well from TT-RSS. Tests welcome if you can - please let me know :-)
We also need to re-test FreshRSS own export / import, as it was modified during the process.

**Comment by typhoe** [comment]
Hi,

I have tested the custom labels import function from TTRSS favorites with labels and it seems to work fine.

I tried the export/import from FreshRSS and didn't notice any problem.

I also tried to import in TTRSS the exported opml from FreshRSS (just had to unzip it first).
It works without problem. I get back the full feeds with theirs categories.

If I have a few suggestions: 
Display the user name currently connected in FreshRSS on the main page or in the dropdown menu (something like "disconnect USER" in place of simply "disconnect"). The user currently connected is only displayed in the profil page for now (isn't it?).
And add it to the name of the FreshRSS export (freshrss_2018-11-05_export.zip -> freshrss_2018-11-05_export_USER.zip)

Thank you.

**Comment by Alkarex** [comment]
Thanks for the test @typhoe 👍 
I will address the other points in another PR.

**Comment by Alkarex** [comment]
@typhoe I have implemented your suggestions in https://github.com/FreshRSS/FreshRSS/pull/2133
Tests welcome

**Pull request merged**
