### PR TITLE
FreshRSS 1.11.1

### PR DESCRIPTION
**Pull request by Alkarex**
[FreshRSS 1.11.1](https://github.com/FreshRSS/FreshRSS/milestones/1.11.1) is a quick fix for a regression introduced in [version 1.11.0](https://github.com/FreshRSS/FreshRSS/pull/1902) and affecting the fetching of full article contents. This version also contains a few more improvements.

[Changelog](https://github.com/FreshRSS/FreshRSS/blob/dev/CHANGELOG.md):

* Features
	* Better support of `media:` tags such as thumbnails and descriptions (e.g. for YouTube) [#944](https://github.com/FreshRSS/FreshRSS/issues/944)
* Extensions
	* New extension mechanism allowing changing HTTP headers and other SimplePie parameters [#1924](https://github.com/FreshRSS/FreshRSS/pull/1924)
	* Built-in extension to fix Tumblr feeds from European Union due to GDPR [#1894](https://github.com/FreshRSS/FreshRSS/issues/1894)
* Bug fixing
	* Fix bug in case of bad i18n in extensions [#1797](https://github.com/FreshRSS/FreshRSS/issues/1797)
	* Fix extension callback for updated articles and PubSubHubbub [#1926](https://github.com/FreshRSS/FreshRSS/issues/1926)
	* Fix regression in fetching full articles content [#1917](https://github.com/FreshRSS/FreshRSS/issues/1917)
	* Fix several bugs in the new Fever API [#1930](https://github.com/FreshRSS/FreshRSS/issues/1930)
	* Updated sharing to Mastodon [#1904](https://github.com/FreshRSS/FreshRSS/issues/1904)

### CODE REVIEW

**Comment by Alkarex** [comment]
@Frenzie If you can, could you please test the /dev branch with one of your extensions?

**Comment by Frenzie** [comment]
@Alkarex I might be able to squeeze it in somewhere today; not sure, no time for sure from Mon-Wed. :-/

**Review by gllmhyt — DISMISSED** [review]
Fixes the automatic feed update that was broken with 1.11.0 and make FreshRSS an amazing software once again.

Getting this warning when running `actualize_script.php`:
```
PHP Warning:  Invalid argument supplied for foreach() in /var/www/freshrss/app/Models/Feed.php on line 388
```

**Comment by GLLM** [comment]
I really need this patch as all my feeds update are now broken.
Some feeds dont react well when I attempt to force update (actualize) them individually. Other do.

Cant wait for the release :)

**Comment by Alkarex** [comment]
@GLLM Probably Saturday. I am only waiting for a little bit more feedback from people testing/using the /dev branch. Otherwise it is ready. You are very welcome to use the /dev branch, by the way. You can think of the /dev branch as a rolling release, while the tags on the master branch are a versioned release.

**Comment by GLLM** [comment]
Hey @Alkarex 
thanks for your reply .... I admit I prefer being on the dev version, to avoid potentiel bugs which could potentially break the DB (and this is something i'd hate).

Moreover, I use the web updater and I'm not sure if I can switch the update channel. Can I ?
If so, can I revert to the stable version (provided it has a higher CL than the dev) afterwards ?
Thanks

**Comment by Alkarex** [comment]
@GLLM If you back-up your DB before the operation, that should be safe enough. You can also install the /dev version in parallel. From master to dev should always be fine, as well as from dev to the next master version (which is what I suggest here). However, going back to older versions can sometime be more hazardous. The Web updater has a number of issues / limitations, and needs to be improved. Git, Docker, manual ZIP methods should all be fine.

**Comment by GLLM** [comment]
@Alkarex : issue solved with v1.11.1 Thanks

**Pull request merged**
