### PR TITLE
Statistics: dynamically resize

### PR DESCRIPTION
**Pull request by Frenzie**
Follow-up on <https://github.com/FreshRSS/FreshRSS/pull/3797>.

It was merged before I could take a look at that last commit. ;-)

### CODE REVIEW

**Comment by Alkarex** [comment]
Sorry @Frenzie  🙈

**Comment by math-GH** [comment]
I would add, that the JavaScript library needs a complete freshup. See my comment in the PR

**Comment by Frenzie** [comment]
Needs is a strong word, but I'll take a look at https://github.com/EnterpriseDB/Flotr2
https://github.com/yurikuzn/Flotr2 which includes a few fixes for Google's idiotic breaking changes.

**Review by aledeg — APPROVED** [review]

**Comment by math-GH** [comment]
It dos not work in "Articles repartition" but in "Main statistics"

**Comment by Frenzie** [comment]
…repartition? Must be Franglais of some sort? :-P

**Comment by Frenzie** [comment]
Basically just `Article statistics`?

**Comment by math-GH** [comment]
> 
> 
> …repartition? Must be Franglais of some sort? :-P

it is also English. I did not knew this word before. I would call it "Article's heartbeat"

**Comment by math-GH** [comment]
For me the 6cdc7e7 did not fix it :/

**Comment by Frenzie** [comment]
> it is also English.

The *word* is English. Almost all Frenglish uses a word that exists in English.

**Comment by Frenzie** [comment]
@mathContao 

> For me the 6cdc7e7 did not fix it :/

That's strange, if you triple checked if your cable's plugged in and all that (Ctrl+F5, double check repartition.js itself, etc.), which browser are you using? If anything works or doesn't work it should be on all pages though. ^_^

**Comment by math-GH** [comment]
now it works. Had mystical troubles with upload/update of these JS file. Sorry for making troubles.

LGTM

**Pull request merged**
