### PR TITLE
keep_max disabled by default for existing installations

### PR DESCRIPTION
**Pull request by Alkarex**
Fix https://github.com/FreshRSS/FreshRSS/issues/2600

### CODE REVIEW

**Comment by Alkarex** [comment]
@Frenzie would you be able to test / double-check? Otherwise I suggest that we merge

**Comment by Frenzie** [comment]
I can probably upgrade another test instance tonight.

Edit: not fully sure though.

**Comment by Alkarex** [comment]
Ok, then let's merge for additional testing (it is in any case less risky than what is in /dev right now)

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/2599

**Comment by Frenzie** [comment]
I just updated 1.14 to the latest dev and it still looks like this:

Screenshot_2019-10-27 Archiving · FreshRSS

**Comment by Alkarex** [comment]
Did not work well. Second attempt https://github.com/FreshRSS/FreshRSS/pull/2607

**Comment by Frenzie** [comment]
Seems to be okay now.

**Pull request merged**
