### PR TITLE
i18n-de: fixed misleading wording.

### PR DESCRIPTION
**Pull request by mro**
PR 2nd try.

thank you for this nice feed-reader.

### CODE REVIEW

**Comment by Alwaysin** [comment]
Thanks for the fix!

However, you should do your PR on the /dev branch, not the master.

**Comment by mro** [comment]
ic, can you cherry-pick the commit, or do I have to redo the PR?

**Comment by Alwaysin** [comment]
I can't, but @Alkarex can and surely will :)

**Comment by Alkarex** [comment]
Done, thanks https://github.com/FreshRSS/FreshRSS/commit/5a2bc9261ca5104022ce64e00d0384791b0443d1

**Pull request closed without merging**
